"""spectralstream.tensor — High-performance tensor operations and HPC engine."""

from __future__ import annotations

from .quantum_sampler import Wavefunction, BornMachineSampler, QuantumResonance
from .tensor_ops_engine import (
    TensorLayout,
    MemoryOrder,
    FusedOperations,
    MatMulKernels,
    NormKernels,
    ActivationKernels,
    SoftmaxKernels,
    ReduceKernels,
    MemoryOperations,
    BatchOperations,
    SpectralOperations,
    SpectralMatmul,
    SpectralGEMM,
    ResonantRoofline,
    VlasovBatchScheduler,
    QuantumSuperpositionEngine,
    HolographicGEMM,
    TensorOps,
    fused_ops,
)
from .hpc_engine import (
    ParallelStrategy,
    WorkStealingThreadPool,
    ProcessPool,
    AsyncEngine,
    SIMDVectorizer,
    CacheOptimizer,
    IoUringEngine,
    NUMABinder,
    GPUDispatch,
    PipelineParallelism,
    ResonantParallelism,
    HolographicLoadBalancer,
    VlasovScheduler,
    QuantumParallelism,
    SelfTuningParallelism,
    HPCContext,
)

__all__ = [
    "Wavefunction",
    "BornMachineSampler",
    "QuantumResonance",
    "TensorLayout",
    "MemoryOrder",
    "FusedOperations",
    "MatMulKernels",
    "NormKernels",
    "ActivationKernels",
    "SoftmaxKernels",
    "ReduceKernels",
    "MemoryOperations",
    "BatchOperations",
    "SpectralOperations",
    "SpectralMatmul",
    "SpectralGEMM",
    "ResonantRoofline",
    "VlasovBatchScheduler",
    "QuantumSuperpositionEngine",
    "HolographicGEMM",
    "TensorOps",
    "fused_ops",
    "ParallelStrategy",
    "WorkStealingThreadPool",
    "ProcessPool",
    "AsyncEngine",
    "SIMDVectorizer",
    "CacheOptimizer",
    "IoUringEngine",
    "NUMABinder",
    "GPUDispatch",
    "PipelineParallelism",
    "ResonantParallelism",
    "HolographicLoadBalancer",
    "VlasovScheduler",
    "QuantumParallelism",
    "SelfTuningParallelism",
    "HPCContext",
]
