from ._sparsity1of2 import Sparsity1of2
from ._sparsity1of4 import Sparsity1of4
from ._sparsity2of4 import Sparsity2of4
from ._sparsity3of4 import Sparsity3of4
from ._sparsity1of8 import Sparsity1of8
from ._sparsity2of8 import Sparsity2of8
from ._sparsity3of8 import Sparsity3of8
from ._sparsity4of8 import Sparsity4of8
from ._sparsity1of16 import Sparsity1of16
from ._sparsity2of16 import Sparsity2of16
from ._sparsity4of16 import Sparsity4of16
from ._sparsity8of16 import Sparsity8of16
from ._randomsparsitypattern import RandomSparsityPattern
from ._structuredsparsitypattern import StructuredSparsityPattern
from ._blocksparsitypattern import BlockSparsityPattern
from ._stridedsparsitypattern import StridedSparsityPattern
from ._diagonalsparsitypattern import DiagonalSparsityPattern
from ._bandedsparsitypattern import BandedSparsityPattern
from ._adaptivesparsitypattern import AdaptiveSparsityPattern
from ._learnedsparsitypattern import LearnedSparsityPattern
from ._blocksize16 import BlockSize16
from ._blocksize32 import BlockSize32
from ._blocksize64 import BlockSize64
from ._blocksize128 import BlockSize128
from ._blocksize256 import BlockSize256
from ._adaptiveblocksize import AdaptiveBlockSize
from ._variableblocksize import VariableBlockSize
from ._hierarchicalblock import HierarchicalBlock
from ._overlappingblock import OverlappingBlock
from ._tiledblock import TiledBlock
from ._stripedblock import StripedBlock
from ._checkerboardblock import CheckerboardBlock
from ._diagonalblock import DiagonalBlock
from ._bandedblock import BandedBlock
from ._outerproductblock import OuterProductBlock
from ._magnitudepruning import MagnitudePruning
from ._randompruning import RandomPruning
from ._gradientpruning import GradientPruning
from ._hessianpruning import HessianPruning
from ._movementpruning import MovementPruning
from ._lotteryticketpruning import LotteryTicketPruning
from ._iterativepruning import IterativePruning
from ._oneshotpruning import OneShotPruning
from ._gradualpruning import GradualPruning
from ._rewindingpruning import RewindingPruning
from ._globalpruning import GlobalPruning
from ._localpruning import LocalPruning
from ._layerwisepruning import LayerwisePruning
from ._thresholdpruning import ThresholdPruning
from ._adaptivepruning import AdaptivePruning
from ._sparseint8 import SparseINT8
from ._sparseint4 import SparseINT4
from ._sparsenf4 import SparseNF4
from ._sparseternary import SparseTernary
from ._sparsebinary import SparseBinary
from ._sparseproductquant import SparseProductQuant
from ._sparseresidualquant import SparseResidualQuant
from ._sparsekmeans import SparseKMeans
from ._blocksparseint8 import BlockSparseINT8
from ._blocksparseint4 import BlockSparseINT4
from ._nmsparseint8 import NMSparseINT8
from ._nmsparseint4 import NMSparseINT4
from ._diagonalsparseint8 import DiagonalSparseINT8
from ._bandedsparseint8 import BandedSparseINT8
from ._randomsparseint8 import RandomSparseINT8
from ._topkweightsparseint4 import TopKWeightSparseINT4
from ._topkblocksparseint4 import TopKBlockSparseINT4
from ._outliersparseint8 import OutlierSparseINT8
from ._structuredsparseint4 import StructuredSparseINT4
from ._adaptivesparsequant import AdaptiveSparseQuant
from ._circulantsparse import CirculantSparse
from ._toeplitzsparse import ToeplitzSparse
from ._hankelsparse import HankelSparse
from ._vandermondesparse import VandermondeSparse
from ._butterflysparse import ButterflySparse
from ._monarchsparse import MonarchSparse
from ._fft_sparse import FFT_Sparse
from ._dct_sparse import DCT_Sparse
from ._waveletsparse import WaveletSparse
from ._hadamardsparse import HadamardSparse
from ._kroneckersparse import KroneckerSparse
from ._cauchysparse import CauchySparse
from ._chebyshevsparse import ChebyshevSparse
from ._legendresparse import LegendreSparse
from ._fouriersparse import FourierSparse
from ._gpu_friendlysparsity import GPU_FriendlySparsity
from ._cpu_friendlysparsity import CPU_FriendlySparsity
from ._simd_sparsity import SIMD_Sparsity
from ._cachefriendlysparsity import CacheFriendlySparsity
from ._memoryalignedsparsity import MemoryAlignedSparsity
from ._vectorizedsparsity import VectorizedSparsity
from ._tensorcoresparsity import TensorCoreSparsity
from ._npu_sparsity import NPU_Sparsity
from ._tpu_sparsity import TPU_Sparsity
from ._fpga_sparsity import FPGA_Sparsity
from ._asic_sparsity import ASIC_Sparsity
from ._mobilesparsity import MobileSparsity
from ._edgesparsity import EdgeSparsity
from ._distributedsparsity import DistributedSparsity
from ._parallelsparsity import ParallelSparsity
from ._dct4x4_quant import DCT4x4_Quant
from ._dct8x8_quant import DCT8x8_Quant
from ._dct16x16_quant import DCT16x16_Quant
from ._dct32x32_quant import DCT32x32_Quant
from ._dct_block4_quant import DCT_Block4_Quant
from ._dct_block8_quant import DCT_Block8_Quant
from ._dct_block16_quant import DCT_Block16_Quant
from ._dct_adaptiveblock_quant import DCT_AdaptiveBlock_Quant
from ._dct_energythreshold_quant import DCT_EnergyThreshold_Quant
from ._dct_zigzag_quant import DCT_Zigzag_Quant
from ._dct_jpeg_quant import DCT_JPEG_Quant
from ._dct_mpeg_quant import DCT_MPEG_Quant
from ._dct_h265_quant import DCT_H265_Quant
from ._dct_av1_quant import DCT_AV1_Quant
from ._dct_vc6_quant import DCT_VC6_Quant
from ._dct_vp9_quant import DCT_VP9_Quant
from ._dct_theora_quant import DCT_Theora_Quant
from ._dct_dirac_quant import DCT_Dirac_Quant
from ._dct_wmv_quant import DCT_WMV_Quant
from ._dct_vc1_quant import DCT_VC1_Quant
from ._haarwavelet_quant import HaarWavelet_Quant
from ._daubechies4_quant import Daubechies4_Quant
from ._daubechies6_quant import Daubechies6_Quant
from ._daubechies8_quant import Daubechies8_Quant
from ._symlet4_quant import Symlet4_Quant
from ._symlet6_quant import Symlet6_Quant
from ._coiflet2_quant import Coiflet2_Quant
from ._coiflet4_quant import Coiflet4_Quant
from ._biorthogonal_quant import Biorthogonal_Quant
from ._reversebiorthogonal_quant import ReverseBiorthogonal_Quant
from ._discretemeyer_quant import DiscreteMeyer_Quant
from ._battlelemarie_quant import BattleLemarie_Quant
from ._splinewavelet_quant import SplineWavelet_Quant
from ._morletwavelet_quant import MorletWavelet_Quant
from ._mexicanhat_quant import MexicanHat_Quant
from ._complexwavelet_quant import ComplexWavelet_Quant
from ._dualtreewavelet_quant import DualTreeWavelet_Quant
from ._waveletpacket_quant import WaveletPacket_Quant
from ._stationarywavelet_quant import StationaryWavelet_Quant
from ._liftingwavelet_quant import LiftingWavelet_Quant
from ._fft_quant import FFT_Quant
from ._rfft_quant import RFFT_Quant
from ._dst_quant import DST_Quant
from ._dht_quant import DHT_Quant
from ._dft_quant import DFT_Quant
from ._fractionalfft_quant import FractionalFFT_Quant
from ._goertzel_quant import Goertzel_Quant
from ._chirpz_quant import ChirpZ_Quant
from ._zoomfft_quant import ZoomFFT_Quant
from ._slidingdft_quant import SlidingDFT_Quant
from ._prunedfft_quant import PrunedFFT_Quant
from ._sparsefft_quant import SparseFFT_Quant
from ._realfft_quant import RealFFT_Quant
from ._complexfft_quant import ComplexFFT_Quant
from ._multidimensionalfft_quant import MultidimensionalFFT_Quant
from ._hadamard_quant import Hadamard_Quant
from ._orderedhadamard_quant import OrderedHadamard_Quant
from ._sequencyhadamard_quant import SequencyHadamard_Quant
from ._dyadichadamard_quant import DyadicHadamard_Quant
from ._walshhadamard_quant import WalshHadamard_Quant
from ._slanthadamard_quant import SlantHadamard_Quant
from ._complexhadamard_quant import ComplexHadamard_Quant
from ._quaternionhadamard_quant import QuaternionHadamard_Quant
from ._fractionalhadamard_quant import FractionalHadamard_Quant
from ._permutedhadamard_quant import PermutedHadamard_Quant
from ._scrambledhadamard_quant import ScrambledHadamard_Quant
from ._adaptivehadamard_quant import AdaptiveHadamard_Quant
from ._blockhadamard_quant import BlockHadamard_Quant
from ._hierarchicalhadamard_quant import HierarchicalHadamard_Quant
from ._mixedradixhadamard_quant import MixedRadixHadamard_Quant
from ._klt_quant import KLT_Quant
from ._adaptiveklt_quant import AdaptiveKLT_Quant
from ._blockklt_quant import BlockKLT_Quant
from ._segmentklt_quant import SegmentKLT_Quant
from ._recursiveklt_quant import RecursiveKLT_Quant
from ._fastklt_quant import FastKLT_Quant
from ._approximateklt_quant import ApproximateKLT_Quant
from ._sparseklt_quant import SparseKLT_Quant
from ._robustklt_quant import RobustKLT_Quant
from ._incrementalklt_quant import IncrementalKLT_Quant
from ._sinetransform_quant import SineTransform_Quant
from ._cosinetransform_quant import CosineTransform_Quant
from ._hartleytransform_quant import HartleyTransform_Quant
from ._hilberttransform_quant import HilbertTransform_Quant
from ._cepstraltransform_quant import CepstralTransform_Quant
from ._mellintransform_quant import MellinTransform_Quant
from ._ztransform_quant import ZTransform_Quant
from ._laplacetransform_quant import LaplaceTransform_Quant
from ._ridgelettransform_quant import RidgeletTransform_Quant
from ._curvelettransform_quant import CurveletTransform_Quant
from ._contourlettransform_quant import ContourletTransform_Quant
from ._shearlettransform_quant import ShearletTransform_Quant
from ._bandlettransform_quant import BandletTransform_Quant
from ._wedgelettransform_quant import WedgeletTransform_Quant
from ._platelettransform_quant import PlateletTransform_Quant
from ._surflettransform_quant import SurfletTransform_Quant
from ._beamlettransform_quant import BeamletTransform_Quant
from ._chordlettransform_quant import ChordletTransform_Quant
from ._arbitrarytransform_quant import ArbitraryTransform_Quant
from ._sequentialdelta import SequentialDelta
from ._framedelta import FrameDelta
from ._interframedelta import InterFrameDelta
from ._intraframedelta import IntraFrameDelta
from ._adaptivedelta import AdaptiveDelta
from ._hierarchicaldelta import HierarchicalDelta
from ._multiscaledelta import MultiScaleDelta
from ._variabledelta import VariableDelta
from ._predictivedelta import PredictiveDelta
from ._bidirectionaldelta import BidirectionalDelta
from ._motioncompensateddelta import MotionCompensatedDelta
from ._weighteddelta import WeightedDelta
from ._sparsedelta import SparseDelta
from ._thresholdeddelta import ThresholdedDelta
from ._quantizeddelta import QuantizedDelta
from ._entropycodeddelta import EntropyCodedDelta
from ._runlengthdelta import RunLengthDelta
from ._dictionarydelta import DictionaryDelta
from ._transformdelta import TransformDelta
from ._hybriddelta import HybridDelta
from ._layerdelta import LayerDelta
from ._interlayerdelta import InterLayerDelta
from ._intralayerdelta import IntraLayerDelta
from ._adjacentlayerdelta import AdjacentLayerDelta
from ._skiplayerdelta import SkipLayerDelta
from ._residuallayerdelta import ResidualLayerDelta
from ._attentiondelta import AttentionDelta
from ._ffn_delta import FFN_Delta
from ._embeddingdelta import EmbeddingDelta
from ._headdelta import HeadDelta
from ._expertdelta import ExpertDelta
from ._shareddelta import SharedDelta
from ._normdelta import NormDelta
from ._biasdelta import BiasDelta
from ._weightdelta import WeightDelta
from ._gradientdelta import GradientDelta
from ._activationdelta import ActivationDelta
from ._blockdelta import BlockDelta
from ._channeldelta import ChannelDelta
from ._rowdelta import RowDelta
from ._linearpredictivedelta import LinearPredictiveDelta
from ._ar_delta import AR_Delta
from ._ma_delta import MA_Delta
from ._arma_delta import ARMA_Delta
from ._kalmandelta import KalmanDelta
from ._particledelta import ParticleDelta
from ._gp_delta import GP_Delta
from ._neuraldelta import NeuralDelta
from ._lstm_delta import LSTM_Delta
from ._attentiondeltapred import AttentionDeltaPred
from ._transformerdelta import TransformerDelta
from ._contextdelta import ContextDelta
from ._adaptivepredictivedelta import AdaptivePredictiveDelta
from ._multisteppredictivedelta import MultiStepPredictiveDelta
from ._errorfeedbackdelta import ErrorFeedbackDelta
from ._gradientdeltapred import GradientDeltaPred
from ._hessiandeltapred import HessianDeltaPred
from ._momentumdeltapred import MomentumDeltaPred
from ._nesterovdelta import NesterovDelta
from ._adamdelta import AdamDelta
from ._rowdeltastructured import RowDeltaStructured
from ._columndelta import ColumnDelta
from ._blockdeltastructured import BlockDeltaStructured
from ._diagonaldelta import DiagonalDelta
from ._bandeddelta import BandedDelta
from ._triangulardelta import TriangularDelta
from ._symmetricdelta import SymmetricDelta
from ._circulantdelta import CirculantDelta
from ._toeplitzdelta import ToeplitzDelta
from ._hankeldelta import HankelDelta
from ._vandermondedelta import VandermondeDelta
from ._cauchydelta import CauchyDelta
from ._permutationdelta import PermutationDelta
from ._kroneckerdelta import KroneckerDelta
from ._butterflydelta import ButterflyDelta
from ._monarchdelta import MonarchDelta
from ._svd_delta import SVD_Delta
from ._cp_delta import CP_Delta
from ._tt_delta import TT_Delta
from ._tucker_delta import Tucker_Delta
from ._adaptivethresholddelta import AdaptiveThresholdDelta
from ._adaptiveblockdelta import AdaptiveBlockDelta
from ._adaptivestepdelta import AdaptiveStepDelta
from ._adaptivequantdelta import AdaptiveQuantDelta
from ._adaptivepredictordelta import AdaptivePredictorDelta
from ._adaptiveerrordelta import AdaptiveErrorDelta
from ._learningratedelta import LearningRateDelta
from ._momentumdelta import MomentumDelta
from ._signdelta import SignDelta
from ._exponentialdelta import ExponentialDelta
from ._logarithmicdelta import LogarithmicDelta
from ._powerdelta import PowerDelta
from ._piecewisedelta import PiecewiseDelta
from ._splinedelta import SplineDelta
from ._interpolatingdelta import InterpolatingDelta
from ._extrapolatingdelta import ExtrapolatingDelta
from ._smoothingdelta import SmoothingDelta
from ._filteringdelta import FilteringDelta
from ._mediandelta import MedianDelta
from ._modedelta import ModeDelta
from ._topksparsity import TopKSparsity
from ._bottomksparsity import BottomKSparsity
from ._percentilesparsity import PercentileSparsity
from ._dynamicsparsity import DynamicSparsity
from ._staticsparsity import StaticSparsity
from ._uniformsparsity import UniformSparsity
from ._erdosrenyisparsity import ErdosRenyiSparsity
from ._powerlawsparsity import PowerLawSparsity
from ._l1sparsity import L1Sparsity
from ._l0sparsity import L0Sparsity
from ._karhunenloeve_quant import KarhunenLoeve_Quant
from ._independentcomponent_quant import IndependentComponent_Quant
from ._principalcomponent_quant import PrincipalComponent_Quant
from ._nonnegativematrix_quant import NonNegativeMatrix_Quant
from ._sparsecoding_quant import SparseCoding_Quant
from ._temporaldelta import TemporalDelta
from ._spatialdelta import SpatialDelta
from ._spatiotemporaldelta import SpatioTemporalDelta
from ._frequencydelta import FrequencyDelta
from ._phasedelta import PhaseDelta
