from __future__ import annotations

# Auto-split: original chaotic_dynamical.py split into chaotic_dynamical/
from ._lorenzsigmaencoding import *
from ._lorenzrhoencoding import *
from ._lorenzbetaencoding import *
from ._lorenzfullparams import *
from ._lorenzadaptivestep import *
from ._lorenztrajectorylength import *
from ._lorenznoiseamplitude import *
from ._lorenzprojectionx import *
from ._lorenzprojectiony import *
from ._lorenzprojectionz import *
from ._lorenzbutterflyeffect import *
from ._lorenzstrangeness import *
from ._lorenzbifurcationnear import *
from ._lorenzlobeswitching import *
from ._lorenzlyapunovestimator import *
from ._lorenzphaseportrait import *
from ._lorenzattractorbasin import *
from ._lorenztransientchaos import *
from ._lorenzrotationsymmetry import *
from ._lorenzenergeticbound import *
from ._lorenzskewsymmetric import *
from ._lorenzconvectionroll import *
from ._lorenzspectralwarming import *
from ._lorenzdissipationrate import *
from ._lorenzfixedpointshift import *
from ._lorenzturbulentmixing import *
from ._rossleraparam import *
from ._rosslerbparam import *
from ._rosslercparam import *
from ._rosslerfullabc import *
from ._rosslerfoldbifurcation import *
from ._rosslerperioddoubling import *
from ._rosslerchaoticattractor import *
from ._rosslerspiraltype import *
from ._rosslerphasecoherent import *
from ._rosslermixingrate import *
from ._rosslermultiscroll import *
from ._rossleramplitudedeath import *
from ._rosslerfrequencylocking import *
from ._rosslerslowmanifold import *
from ._rosslerspiralsaddle import *
from ._rosslertransversestability import *
from ._henonaparam import *
from ._henonbparam import *
from ._henonfullab import *
from ._henonstrangeattractor import *
from ._henonbasinboundary import *
from ._henonperiodicwindow import *
from ._henoncrisisroute import *
from ._henonintermittency import *
from ._henonattractordimension import *
from ._henondissipative import *
from ._henontimereversal import *
from ._henonsingularity import *
from ._henonunstableperiodic import *
from ._henontangentspace import *
from ._henonboundedescape import *
from ._henongeneralized import *
from ._hamiltonianharmonicosc import *
from ._hamiltoniananharmonic import *
from ._hamiltoniandoublewell import *
from ._hamiltoniantriplewell import *
from ._hamiltoniankepler import *
from ._hamiltonianpendulum import *
from ._hamiltonianenergyconserving import *
from ._hamiltoniansymplecticeuler import *
from ._hamiltonianleapfrog import *
from ._hamiltonianseparable import *
from ._hamiltoniannonseparable import *
from ._hamiltonianphasespacevolume import *
from ._hamiltonianpoissonbracket import *
from ._hamiltonianadiabaticinvariant import *
from ._hamiltonianmagneticfield import *
from ._hamiltoniankamtorus import *
from ._hamiltonianactionangle import *
from ._hamiltoniannonholonomic import *
from ._hamiltoniannoether import *
from ._hamiltoniancentralforce import *
from ._lagrangianminaction import *
from ._lagrangianfreeparticle import *
from ._lagrangianharmonic import *
from ._lagrangiancoupledosc import *
from ._lagrangiannonlinearspring import *
from ._lagrangianactionangle import *
from ._lagrangianeulerlagrange import *
from ._lagrangiannoethercurrent import *
from ._lagrangianvelocitydependent import *
from ._lagrangianmultipleparticles import *
from ._lagrangianconstrained import *
from ._lagrangianfriction import *
from ._lagrangiandrivenosc import *
from ._lagrangianparametricresonance import *
from ._lagrangianresonancecapture import *
from ._lagrangiandoublewell import *
from ._kuromotosynchronization import *
from ._kuromotofrequencyspread import *
from ._kuromotooscillatorcount import *
from ._kuromotoorderparameter import *
from ._kuromotophasetransition import *
from ._kuromotopartialsynchrony import *
from ._kuromotochimerastate import *
from ._kuromotoexplosivesync import *
from ._kuromotomulticluster import *
from ._kuromotodelaycoupling import *
from ._kuromotoadaptivenetworks import *
from ._kuromotofrustrated import *
from ._kuromotoweightedcoupling import *
from ._kuromotonoiseinduced import *
from ._kuromotospatialcoupling import *
from ._kuromotohierarchical import *
from ._kuromotobistable import *
from ._kuromotopulsecoupled import *
from ._kuromotometabolic import *
from ._kuromotophaseresponse import *
from ._kuromotomeanfield import *
from ._kuromotogloballycoupled import *
from ._doublependulumgravity import *
from ._doublependuluml1 import *
from ._doublependuluml2 import *
from ._doublependulumtimestep import *
from ._doublependuluminitialangle1 import *
from ._doublependuluminitialangle2 import *
from ._doublependulumchaoticity import *
from ._doublependulumenergyexchange import *
from ._doublependulumpoincare import *
from ._doublependulumtorque import *
from ._doublependulumdamping import *
from ._doublependulumasymmetric import *
from ._doublependulumspringcoupling import *
from ._doublependulumnonlinearrestoring import *
from ._doublependulumparametricdrive import *
from ._doublependulummagneticperturbation import *
from ._logisticbifurcationparam import *
from ._logisticinitialcondition import *
from ._logisticcascadedepth import *
from ._logisticperioddoubling import *
from ._logisticchaoticregime import *
from ._logistictangentbifurcation import *
from ._logisticbandedchaos import *
from ._logisticlyapunovestimate import *
from ._logisticsuperstable import *
from ._logisticcoupledmaps import *
from ._logisticnoiseperturbed import *
from ._logisticgeneralized import *
from ._logisticintermittency import *
from ._logisticbistablecascade import *
from ._logistichigherorder import *
from ._logisticfeigenbaum import *
from ._multistablebistableswitch import *
from ._multistabletristable import *
from ._multistablebasinhopping import *
from ._multistableattractorrivalry import *
from ._multistablepotentiallandscape import *
from ._multistablecuspcatastrophe import *
from ._multistablehysteresisloop import *
from ._multistablespinodaldecomp import *
from ._multistablehomoclinicbif import *
from ._multistablefitzhughnagumo import *
from ._multistablelorenzcompetition import *
from ._multistablegeneralizedmultistability import *
from ._multistablepitchfork import *
from ._multistablesaddlenode import *
from ._multistablesubcriticalpitchfork import *
from ._multistablesnic import *
from ._heteroclinicsaddlechain import *
from ._heterocliniccycle import *
from ._heteroclinicsaddleconnection import *
from ._heteroclinictemporalcode import *
from ._heteroclinicsequentialswitch import *
from ._heteroclinicwinnerlesscompe import *
from ._heterocliniclotkavolterra import *
from ._heteroclinicsaddlenodeloop import *
from ._heteroclinicshilnikov import *
from ._heteroclinicghost import *
from ._heteroclinicbursting import *
from ._heteroclinictorusbreakdown import *
from ._heteroclinicfoldhopf import *
from ._heteroclinicbluesky import *
from ._heteroclinicchaoticitinerancy import *
from ._heteroclinicriddledbasin import *
from ._hybridlorenzrossler import *
from ._hybridlogistichenon import *
from ._hybridhamiltonianlogistic import *
from ._hybridkuromotologistic import *
from ._hybriddoublependulumlorenz import *
from ._hybridrosslerhenon import *
from ._hybridthreewaycoupling import *
from ._hybridswitchablesystem import *
from ._hybridcascade import *
from ._hybridattractormodulated import *
from ._hybridsynchronizedchaos import *
from ._hybridchaoscontrol import *
from ._hybridmultiscalecoupling import *
from ._hybridrecurrentattractor import *
from ._hybridstochasticresonance import *
from ._hybridextremeevents import *
from ._hybridtwoscalecoupling import *
from ._hybridadaptivecoupling import *
from ._hybridcoupledlogisticlattice import *
from ._hybriddelaydifferential import *
from ._hybridasymmetriccoupling import *
from ._hybridrandomdynamical import *
from ._hybridmorrislecar import *
from ._hybridhindmarshrose import *

__all__ = ['_rhdr', '_henon', '_ser', 'LorenzSigmaEncoding', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LorenzRhoEncoding', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'LorenzBetaEncoding', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', 'LorenzFullParams', '_ser', '_henon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LorenzAdaptiveStep', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LorenzTrajectoryLength', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LorenzNoiseAmplitude', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LorenzProjectionX', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LorenzProjectionY', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LorenzProjectionZ', '_svd_core', '_rossler', '_logistic', '_lorenz', '_hdr', '_recon', 'LorenzButterflyEffect', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LorenzStrangeness', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LorenzBifurcationNear', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LorenzLobeSwitching', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'LorenzLyapunovEstimator', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'LorenzPhasePortrait', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LorenzAttractorBasin', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', 'LorenzTransientChaos', '_rossler', '_lorenz', '_hdr', '_recon', 'LorenzRotationSymmetry', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LorenzEnergeticBound', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LorenzSkewSymmetric', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LorenzConvectionRoll', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_recon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', 'LorenzSpectralWarming', '_rhdr', '_henon', '_ser', 'LorenzDissipationRate', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LorenzFixedPointShift', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', 'LorenzTurbulentMixing', '_hdr', '_recon', '_rhdr', 'RosslerAParam', '_ser', '_henon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'RosslerBParam', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'RosslerCParam', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'RosslerFullABC', '_lorenz', '_hdr', '_recon', 'RosslerFoldBifurcation', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'RosslerPeriodDoubling', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'RosslerChaoticAttractor', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'RosslerSpiralType', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'RosslerPhaseCoherent', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', 'RosslerMixingRate', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'RosslerMultiScroll', '_lorenz', '_hdr', '_recon', 'RosslerAmplitudeDeath', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'RosslerFrequencyLocking', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', 'RosslerSlowManifold', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', 'RosslerSpiralSaddle', '_ser', '_henon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'RosslerTransverseStability', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HenonAParam', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', 'HenonBParam', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', 'HenonFullAB', '_ser', '_henon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HenonStrangeAttractor', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HenonBasinBoundary', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HenonPeriodicWindow', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'HenonCrisisRoute', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HenonIntermittency', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'HenonAttractorDimension', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HenonDissipative', '_svd_core', '_rossler', '_logistic', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HenonTimeReversal', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HenonSingularity', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HenonUnstablePeriodic', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_recon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', 'HenonTangentSpace', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', 'HenonBoundedEscape', '_rossler', '_lorenz', '_hdr', '_recon', 'HenonGeneralized', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', 'HamiltonianHarmonicOsc', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HamiltonianAnharmonic', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', 'HamiltonianDoubleWell', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HamiltonianTripleWell', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', 'HamiltonianKepler', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'HamiltonianPendulum', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HamiltonianEnergyConserving', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'HamiltonianSymplecticEuler', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_recon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', 'HamiltonianLeapfrog', '_rhdr', '_henon', '_ser', 'HamiltonianSeparable', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HamiltonianNonSeparable', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HamiltonianPhaseSpaceVolume', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_lorenz', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'HamiltonianPoissonBracket', '_hdr', '_recon', 'HamiltonianAdiabaticInvariant', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', 'HamiltonianMagneticField', '_ser', '_henon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', 'HamiltonianKAMTorus', '_ser', '_henon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', 'HamiltonianActionAngle', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', 'HamiltonianNonHolonomic', '_ser', '_henon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', 'HamiltonianNoether', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HamiltonianCentralForce', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'LagrangianMinAction', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LagrangianFreeParticle', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_hdr', '_logistic', '_svd_core', '_rossler', '_lorenz', 'LagrangianHarmonic', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', 'LagrangianCoupledOsc', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LagrangianNonlinearSpring', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LagrangianActionAngle', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'LagrangianEulerLagrange', '_lorenz', '_hdr', '_recon', 'LagrangianNoetherCurrent', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', 'LagrangianVelocityDependent', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LagrangianMultipleParticles', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', 'LagrangianConstrained', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'LagrangianFriction', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LagrangianDrivenOsc', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_hdr', '_logistic', '_svd_core', '_rossler', '_lorenz', 'LagrangianParametricResonance', '_recon', 'LagrangianResonanceCapture', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'LagrangianDoubleWell', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'KuromotoSynchronization', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'KuromotoFrequencySpread', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'KuromotoOscillatorCount', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'KuromotoOrderParameter', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'KuromotoPhaseTransition', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_recon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', 'KuromotoPartialSynchrony', '_rhdr', '_henon', '_ser', 'KuromotoChimeraState', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', 'KuromotoExplosiveSync', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'KuromotoMultiCluster', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'KuromotoDelayCoupling', '_svd_core', '_rossler', '_logistic', '_lorenz', '_hdr', '_recon', '_lorenz', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'KuromotoAdaptiveNetworks', '_hdr', '_recon', '_rhdr', 'KuromotoFrustrated', '_ser', '_henon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'KuromotoWeightedCoupling', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'KuromotoNoiseInduced', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', 'KuromotoSpatialCoupling', '_recon', '_rhdr', '_henon', '_ser', 'KuromotoHierarchical', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', 'KuromotoBistable', '_ser', '_henon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'KuromotoPulseCoupled', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'KuromotoMetabolic', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'KuromotoPhaseResponse', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'KuromotoMeanField', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', 'KuromotoGloballyCoupled', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', 'DoublePendulumGravity', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', 'DoublePendulumL1', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', 'DoublePendulumL2', '_recon', '_rhdr', 'DoublePendulumTimestep', '_ser', '_henon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'DoublePendulumInitialAngle1', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'DoublePendulumInitialAngle2', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'DoublePendulumChaoticity', '_lorenz', '_hdr', '_recon', 'DoublePendulumEnergyExchange', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', 'DoublePendulumPoincare', '_ser', '_henon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'DoublePendulumTorque', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'DoublePendulumDamping', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'DoublePendulumAsymmetric', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'DoublePendulumSpringCoupling', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'DoublePendulumNonlinearRestoring', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_recon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', 'DoublePendulumParametricDrive', 'DoublePendulumMagneticPerturbation', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LogisticBifurcationParam', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', 'LogisticInitialCondition', '_recon', 'LogisticCascadeDepth', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'LogisticPeriodDoubling', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LogisticChaoticRegime', '_svd_core', '_rossler', '_logistic', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LogisticTangentBifurcation', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LogisticBandedChaos', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LogisticLyapunovEstimate', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', 'LogisticSuperstable', '_ser', '_henon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', 'LogisticCoupledMaps', '_hdr', '_recon', '_lorenz', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'LogisticNoisePerturbed', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LogisticGeneralized', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LogisticIntermittency', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', 'LogisticBistableCascade', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LogisticHigherOrder', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'LogisticFeigenbaum', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_hdr', '_logistic', '_svd_core', '_rossler', '_lorenz', 'MultiStableBistableSwitch', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'MultiStableTristable', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'MultiStableBasinHopping', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', 'MultiStableAttractorRivalry', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'MultiStablePotentialLandscape', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', 'MultiStableCuspCatastrophe', '_rossler', '_lorenz', '_hdr', '_recon', 'MultiStableHysteresisLoop', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'MultiStableSpinodalDecomp', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'MultiStableHomoclinicBif', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'MultiStableFitzHughNagumo', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'MultiStableLorenzCompetition', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'MultiStableGeneralizedMultistability', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'MultiStablePitchfork', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'MultiStableSaddleNode', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'MultiStableSubcriticalPitchfork', '_lorenz', '_hdr', '_recon', '_rhdr', 'MultiStableSNIC', '_ser', '_henon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'HeteroclinicSaddleChain', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'HeteroclinicCycle', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', 'HeteroclinicSaddleConnection', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HeteroclinicTemporalCode', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', 'HeteroclinicSequentialSwitch', '_hdr', '_recon', 'HeteroclinicWinnerlessCompe', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HeteroclinicLotkaVolterra', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HeteroclinicSaddleNodeLoop', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_recon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', 'HeteroclinicShilnikov', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', 'HeteroclinicGhost', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'HeteroclinicBursting', '_lorenz', '_hdr', '_recon', 'HeteroclinicTorusBreakdown', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', 'HeteroclinicFoldHopf', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', 'HeteroclinicBlueSky', '_ser', '_henon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'HeteroclinicChaoticItinerancy', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HeteroclinicRiddledBasin', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HybridLorenzRossler', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_hdr', '_logistic', '_svd_core', '_rossler', '_lorenz', 'HybridLogisticHenon', '_recon', '_rhdr', '_henon', '_ser', 'HybridHamiltonianLogistic', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'HybridKuromotoLogistic', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HybridDoublePendulumLorenz', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'HybridRosslerHenon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'HybridThreeWayCoupling', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HybridSwitchableSystem', '_svd_core', '_rossler', '_logistic', '_lorenz', '_hdr', '_recon', '_lorenz', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'HybridCascade', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'HybridAttractorModulated', '_lorenz', '_hdr', '_recon', 'HybridSynchronizedChaos', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_recon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', 'HybridChaosControl', '_rhdr', '_henon', '_ser', 'HybridMultiscaleCoupling', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', 'HybridRecurrentAttractor', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_recon', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', 'HybridStochasticResonance', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'HybridExtremeEvents', '_lorenz', '_hdr', '_recon', 'HybridTwoScaleCoupling', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HybridAdaptiveCoupling', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', 'HybridCoupledLogisticLattice', '_hdr', '_recon', '_rhdr', '_henon', 'HybridDelayDifferential', '_ser', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'HybridAsymmetricCoupling', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', 'HybridRandomDynamical', '_logistic', '_svd_core', '_rossler', '_lorenz', '_hdr', '_recon', '_rhdr', '_henon', '_ser', '_hdr', '_logistic', '_svd_core', '_rossler', '_lorenz', 'HybridMorrisLecar', '_recon', '_lorenz', '_rhdr', '_henon', '_ser', '_logistic', '_svd_core', '_rossler', 'HybridHindmarshRose', '_hdr', '_recon']
