from __future__ import annotations

# Auto-split: original novel_compression_library.py split into novel_compression_library/
from ._compressionmethod import *
from ._ttsvd import *
from ._ttor import *
from ._trsvd import *
from ._cpals import *
from ._tuckersvd import *
from ._blocktucker import *
from ._hierarchicaltucker import *
from ._tensornetwork import *
from ._butterflyfactorization import *
from ._kroneckerproduct import *
from ._blockdiagonal import *
from ._circulantapprox import *
from ._toeplitzapprox import *
from ._hankelapprox import *
from ._lotr import *
from ._lloydmaxquant import *
from ._adaptivescalarquant import *
from ._productquantization import *
from ._residualvectorquant import *
from ._additivecodebookquant import *
from ._e8latticequant import *
from ._latticequantanchored import *
from ._mixedprecisionquant import *
from ._hessianawarequant import *
from ._fisherinfoquant import *
from ._gptqlayerquant import *
from ._awqactivationaware import *
from ._binaryquant import *
from ._ternaryquant import *
from ._nf4quant import *
from ._dctspectral import *
from ._dct2dblock import *
from ._waveletthreshold import *
from ._fwhtcompress import *
from ._randomizedhadamard import *
from ._winogradtransform import *
from ._nttcompress import *
from ._randomrotationquant import *
from ._butterflysparsetransform import *
from ._sparserandomprojection import *
from ._structuredsparsity import *
from ._blocksparsity import *
from ._unstructuredpruning import *
from ._sparsegpt import *
from ._wandapruning import *
from ._dynamicnmsparsity import *
from ._channelpruning import *
from ._grouplasso import *
from ._adaptivesparsityalloc import *
from ._sparsequantizecombined import *
from ._huffmancoding import *
from ._rans import *
from ._tans import *
from ._arithmeticcoding import *
from ._lz77entropy import *
from ._vlasovmeanfield import *
from ._holographicphaseencoding import *
from ._quantumtensornetwork import *
from ._timecrystalphase import *
from ._plasmafielddecomposition import *
from ._spectraldensityestimation import *
from ._informationbottleneck import *
from ._ratedistortionoptimal import *
from ._fisherraocompression import *
from ._symplecticweightevolution import *
from ._landauzenersampling import *
from ._boltzmannencoding import *
from ._maxentropycompression import *
from ._crosslayerdelta import *
from ._hierarchicalclusteredpq import *
from ._benchmarkresult import *
from ._compressionmethodbenchmark import *

__all__ = ['CompressionMethod', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'TTSVD', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'TTOR', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', 'TRSVD', '_restore_shape', '_safe_bytes', '_ensure_2d', 'CPALS', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', 'TuckerSVD', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'BlockTucker', 'HierarchicalTucker', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'TensorNetwork', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'ButterflyFactorization', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', 'KroneckerProduct', '_ensure_2d', '_register_all', 'BlockDiagonal', '_restore_shape', '_safe_bytes', '_ensure_2d', 'CirculantApprox', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'ToeplitzApprox', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', 'HankelApprox', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'LoTR', 'LloydMaxQuant', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'AdaptiveScalarQuant', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'ProductQuantization', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'ResidualVectorQuant', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', 'AdditiveCodebookQuant', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', 'E8LatticeQuant', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', 'LatticeQuantAnchored', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', 'MixedPrecisionQuant', '_ensure_2d', '_register_all', '_restore_shape', 'HessianAwareQuant', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', 'FisherInfoQuant', '_ensure_2d', 'GPTQLayerQuant', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', 'AWQActivationAware', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', 'BinaryQuant', '_ensure_2d', 'TernaryQuant', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'NF4Quant', 'DCTSpectral', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'DCT2DBlock', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'WaveletThreshold', '_register_all', 'FWHTCompress', '_restore_shape', '_safe_bytes', '_ensure_2d', 'RandomizedHadamard', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'WinogradTransform', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'NTTCompress', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'RandomRotationQuant', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', 'ButterflySparseTransform', '_restore_shape', '_safe_bytes', '_ensure_2d', 'SparseRandomProjection', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'StructuredSparsity', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'BlockSparsity', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'UnstructuredPruning', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'SparseGPT', '_register_all', '_restore_shape', 'WandaPruning', '_safe_bytes', '_ensure_2d', '_register_all', 'DynamicNMSparsity', '_restore_shape', '_safe_bytes', '_ensure_2d', 'ChannelPruning', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', 'GroupLasso', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', 'AdaptiveSparsityAlloc', '_ensure_2d', 'SparseQuantizeCombined', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'HuffmanCoding', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'RANS', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'TANS', '_register_all', '_restore_shape', '_safe_bytes', 'ArithmeticCoding', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'LZ77Entropy', '_register_all', 'VlasovMeanField', '_restore_shape', '_safe_bytes', '_ensure_2d', 'HolographicPhaseEncoding', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'QuantumTensorNetwork', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', 'TimeCrystalPhase', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', 'PlasmaFieldDecomposition', '_ensure_2d', 'SpectralDensityEstimation', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', 'InformationBottleneck', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'RateDistortionOptimal', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'FisherRaoCompression', 'SymplecticWeightEvolution', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'LandauZenerSampling', '_register_all', '_restore_shape', 'BoltzmannEncoding', '_safe_bytes', '_ensure_2d', 'MaxEntropyCompression', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', 'CrossLayerDelta', '_safe_bytes', '_ensure_2d', 'HierarchicalClusteredPQ', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', 'BenchmarkResult', '_register_all', '_restore_shape', '_safe_bytes', '_ensure_2d', '_register_all', '_restore_shape', '_safe_bytes', 'CompressionMethodBenchmark', '_ensure_2d']
