from spectralstream.kv_cache.core import (
    EPS,
    _E8_GENERATOR,
    _E8_VORONOI,
    _e8_quantize_batch,
    _generate_random_hd_vector,
    CacheMetrics,
    QualityMetrics,
    KVCacheConfig,
    KVCacheEntry,
    KVCacheMethod,
)
from spectralstream.kv_cache.compressor import CacheCompressor
from spectralstream.kv_cache.eviction import (
    EvictionPolicy,
    CascadeEviction,
    SpectralEviction,
    H2OEviction,
    SlidingWindowEviction,
    StreamingLLMEviction,
    ResonanceEviction,
    EntropyEviction,
    ImportanceScoring,
    PredictiveEviction,
    ClusteringEviction,
    TopologicalEviction,
    ReinforcementLearningEviction,
    HybridEviction,
    StalenessAwareEviction,
    AccessPatternEviction,
    EntropyGradient,
)
from spectralstream.kv_cache.manager import KVCacheManager
from spectralstream.kv_cache.intelligence_engine import (
    KVCacheIntelligenceEngine,
    KVCacheIntelligenceConfig,
)
from spectralstream.kv_cache.attention import CachedAttention, SmartCacheRouter
from spectralstream.kv_cache.spectral import (
    BAND_HIGH,
    BAND_NORMAL,
    BAND_LOW,
    BAND_COMPRESSION,
    CacheEntry,
    HolographicKVStorage,
    VlasovFieldCache,
    QuantumSuperpositionCache,
    SpectralMultiBandStorage,
    AR2PredictiveCache,
    KIVIHybridQuantizer,
    ResonanceTracker,
    SpectralKVCache,
    ResidualCodec,
    FreqKVExtremeCompressor,
    PlasmaConfinementKVEvictor,
    PredictiveCodingKVCache_v2,
    SpectralSuperpositionKVCache,
    TimeCrystalKVCache_v2,
    ExtremeTieredKVCache,
    KVQualityValidator,
)

__all__ = [
    "PageInfo",
    "RadixNode",
    "PagedKVCache",
    "RadixTreeCache",
    "TierLevel",
    "TierEntry",
    "TieredKVCache",
    "SpectralKVCache_v2",
    "SpectralResonanceCache",
    "HolographicTimeCrystal",
    "FractalCache",
    "AttentionWeightedEviction",
    "SharedPrefixManager",
    "EPS",
    "_E8_GENERATOR",
    "_E8_VORONOI",
    "_e8_quantize_batch",
    "_generate_random_hd_vector",
    "CacheMetrics",
    "QualityMetrics",
    "KVCacheConfig",
    "KVCacheEntry",
    "KVCacheMethod",
    "CacheCompressor",
    "EvictionPolicy",
    "CascadeEviction",
    "SpectralEviction",
    "H2OEviction",
    "SlidingWindowEviction",
    "StreamingLLMEviction",
    "ResonanceEviction",
    "EntropyEviction",
    "ImportanceScoring",
    "PredictiveEviction",
    "ClusteringEviction",
    "TopologicalEviction",
    "ReinforcementLearningEviction",
    "HybridEviction",
    "StalenessAwareEviction",
    "AccessPatternEviction",
    "EntropyGradient",
    "KVCacheManager",
    "CachedAttention",
    "SmartCacheRouter",
    "UnifiedKVCache",
    "UnifiedKVCacheConfig",
    "Strategy",
    "create_unified_kv_cache",
    "BAND_HIGH",
    "BAND_NORMAL",
    "BAND_LOW",
    "BAND_COMPRESSION",
    "CacheEntry",
    "HolographicKVStorage",
    "VlasovFieldCache",
    "QuantumSuperpositionCache",
    "SpectralMultiBandStorage",
    "AR2PredictiveCache",
    "KIVIHybridQuantizer",
    "ResonanceTracker",
    "SpectralKVCache",
    "ResidualCodec",
    "FreqKVExtremeCompressor",
    "PlasmaConfinementKVEvictor",
    "PredictiveCodingKVCache_v2",
    "SpectralSuperpositionKVCache",
    "TimeCrystalKVCache_v2",
    "ExtremeTieredKVCache",
    "KVQualityValidator",
    "KIVICache",
    "GEARCache",
    "FreqKVCache",
    "HolographicKVCache",
    "CrossHeadKVCache",
    "PredictiveKVCache",
    "UnifiedKVCompressor",
    "PerChannelKIVI",
    "GEARTriple",
    "FreqKVPlus",
    "HolographicPhaseKV",
    "CrossHeadCorrelation",
    "PredictiveARModel",
    "SpectralEviction",
    "StreamingSummary",
    "AdaptivePrecision",
    "CrossLayerSharing",
    "KVCacheBenchmark",
    "UltimateKVCache",
    "run_validation",
]
from .paged import (
    PageInfo,
    RadixNode,
    PagedKVCache,
    RadixTreeCache,
    TierLevel,
    TierEntry,
    TieredKVCache,
    SpectralKVCache_v2,
)
from .novel import (
    SpectralResonanceCache,
    HolographicTimeCrystal,
    FractalCache,
    AttentionWeightedEviction,
    SharedPrefixManager,
)
from .compressor import *  # auto-split re-export
from .v2 import (
    KIVICache,
    GEARCache,
    FreqKVCache,
    HolographicKVCache,
    CrossHeadKVCache,
    PredictiveKVCache,
    UnifiedKVCompressor,
)

try:
    from .ultimate import (
        PerChannelKIVI,
        GEARTriple,
        FreqKVPlus,
        HolographicPhaseKV,
        CrossHeadCorrelation,
        PredictiveARModel,
        SpectralEviction,
        StreamingSummary,
        AdaptivePrecision,
        CrossLayerSharing,
        KVCacheBenchmark,
        UltimateKVCache,
        run_validation,
    )
except ImportError:
    (
        PerChannelKIVI,
        GEARTriple,
        FreqKVPlus,
        HolographicPhaseKV,
        CrossHeadCorrelation,
        PredictiveARModel,
        SpectralEviction,
        StreamingSummary,
        AdaptivePrecision,
        CrossLayerSharing,
        KVCacheBenchmark,
        UltimateKVCache,
        run_validation,
    ) = (None,) * 13

# ── Backward-compat aliases ────────────────────────────────────────────
import warnings as _warnings

with _warnings.catch_warnings():
    _warnings.simplefilter("ignore", DeprecationWarning)
    try:
        from spectralstream.unified_kv_cache import (
            UnifiedKVCache,
            UnifiedKVCacheConfig,
            Strategy,
            create_unified_kv_cache,
        )
    except ImportError:
        UnifiedKVCache = None  # type: ignore
        UnifiedKVCacheConfig = None  # type: ignore
        Strategy = None  # type: ignore
        create_unified_kv_cache = None  # type: ignore
