from __future__ import annotations

# Auto-split: original revolutionary_gauge.py split into revolutionary_gauge/
from ._gaugefixedsvd import *
from ._gaugeequivariantfft import *
from ._gaugeinvariantpca import *
from ._gaugeconnection import *
from ._gaugecurvature import *
from ._gaugeholonomy import *
from ._gaugewilsonloop import *
from ._gaugeparalleltransport import *
from ._gaugecovariantderivative import *
from ._gaugefiberbundle import *
from ._gaugesection import *
from ._gaugetransition import *
from ._gaugecech import *
from ._gaugesheaf import *
from ._gaugedifferential import *
from ._gaugeintegral import *
from ._gaugemagnetic import *
from ._gaugeelectric import *
from ._gaugemaxwell import *
from ._gaugeyangmills import *
from ._gaugeinstantons import *
from ._gaugemonopole import *
from ._gaugevortex import *
from ._gaugetopologicalcharge import *
from ._gaugechernsimons import *
from ._gaugebrst import *
from ._gaugeghost import *
from ._gaugefaddeevpopov import *
from ._gaugeanomaly import *
from ._gaugewesszumino import *
from ._gaugetopologicalfield import *
from ._gaugedonaldson import *
from ._gaugeseibergwitten import *
from ._gaugefloer import *
from ._gaugemodulispace import *
from ._gaugeflatconnection import *
from ._gaugeantiselfdual import *
from ._gaugehermitian import *
from ._gaugestablebundle import *
from ._gaugehiggsbundle import *
from ._gaugespectralcover import *
from ._gaugelanglands import *
from ._gaugesmatrix import *
from ._gaugescattering import *
from ._gaugetwistor import *
from ._gaugepenrose import *
from ._gaugespinnetwork import *
from ._gaugespinfoam import *
from ._gaugeloopquantum import *
from ._gaugeareaoperator import *
from ._gaugevolumeoperator import *
from ._gaugehamiltonianconstraint import *
from ._gaugediffeoconstraint import *
from ._gaugeashtekar import *
from ._gaugebarbero import *
from ._gaugeholst import *
from ._gaugepalatini import *
from ._gaugetetrad import *
from ._gaugespinconnection import *
from ._gaugecartan import *
from ._gaugemaurercartan import *
from ._gaugeliederivative import *
from ._gaugekilling import *
from ._gaugeisometry import *
from ._gaugesymplectic import *
from ._gaugekahler import *
from ._gaugecalabiyau import *
from ._gaugespecialholonomy import *
from ._gaugeg2manifold import *
from ._gaugespin7 import *
from ._gaugeexceptional import *
from ._gaugee8 import *
from ._gaugeso32 import *
from ._gaugestringworldsheet import *
from ._gaugedbneumann import *
from ._gaugens5brane import *
from ._gaugem2brane import *
from ._gaugem5brane import *
from ._gaugesusy import *
from ._gaugesuperfield import *
from ._gaugesuperconnection import *
from ._gaugesupercurvature import *
from ._gaugesuperyangmills import *
from ._gaugesupergravity import *
from ._gaugeconformal import *
from ._gaugeweyl import *
from ._gaugescale import *
from ._gaugeconformalblock import *
from ._gaugevertexoperator import *
from ._gaugecurrentalgebra import *
from ._gaugewzw import *
from ._gaugekacmoody import *
from ._gaugevirasoro import *
from ._gaugecentralcharge import *
from ._gaugemodularinvariant import *
from ._gaugerationalcft import *
from ._gaugecosetmodel import *
from ._gaugegepner import *
from ._gaugeorbifold import *
from ._gaugetoric import *
from ._gaugechernweil import *
from ._gaugecherncharacter import *
from ._gaugepontryagin import *
from ._gaugeeuler import *
from ._gaugestiefelwhitney import *
from ._gaugewuclass import *
from ._gaugesteenrodsquare import *
from ._gaugetodd import *
from ._gaugearous import *
from ._gaugeade import *
from ._gaugeaffine import *
from ._gaugealmostcomplex import *
from ._gaugeatiyahsinger import *
from ._gaugebogomolny import *
from ._gaugebps import *
from ._gaugebtzblackhole import *
from ._gaugebundlegerbe import *
from ._gaugecanonical import *
from ._gaugecausal import *
from ._gaugecechdifferential import *
from ._gaugecharacteristic import *
from ._gaugechiral import *
from ._gaugecohomological import *
from ._gaugecompact import *
from ._gaugecomplexstructure import *
from ._gaugecoulomb import *
from ._gaugecovariantstring import *
from ._gaugecritical import *
from ._gaugecycompactification import *
from ._gaugederham import *
from ._gaugedirac import *
from ._gaugediracmonopole import *
from ._gaugedoublecopy import *
from ._gaugedual import *
from ._gaugedualitygroup import *
from ._gaugeeinstein import *
from ._gaugeeinsteinmaxwell import *
from ._gaugeelectroweak import *
from ._gaugeequivariantindex import *
from ._gaugeetainvariant import *
from ._gaugeftheory import *
from ._gaugefibermetric import *
from ._gaugefreedman import *
from ._gaugefrobenius import *
from ._gaugefubinistudy import *
from ._gaugeg2holonomy import *
from ._gaugegaugino import *
from ._gaugegelfandnaimark import *
from ._gaugeginzburglandau import *
from ._gaugegluon import *
from ._gaugegno import *
from ._gaugegodstone import *
from ._gaugegraviphoton import *
from ._gaugegraviton import *
from ._gaugegreenschwarz import *
from ._gaugegrothendieckriemannroch import *
from ._gaugegroupcohomology import *
from ._gaugegut import *
from ._gaugeharmonic import *
from ._gaugeharmonicmap import *
from ._gaugeheterotic import *
from ._gaugehirzebruch import *
from ._gaugehodgestar import *
from ._gaugehyperkahler import *
from ._gaugeindextheorem import *
from ._gaugeintegrablesystem import *
from ._gaugeinteracting import *
from ._gaugeintersection import *
from ._gaugejunction import *
from ._gaugek3 import *
from ._gaugekaluzaklein import *
from ._gaugekodaira import *
from ._gaugelandauginzburg import *
from ._gaugelargen import *
from ._gaugelattice import *
from ._gaugelichnerowicz import *
from ._gaugelocalization import *
from ._gaugelorentz import *
from ._gaugemacdowellmansouri import *
from ._gaugemajorana import *
from ._gaugemassive import *
from ._gaugematrixmodel import *
from ._gaugemembrane import *
from ._gaugeminimal import *
from ._gaugemirrorsymmetry import *
from ._gaugemonodromy import *
from ._gaugemultiloop import *
from ._gaugenahm import *
from ._gaugenambugoto import *
from ._gaugeneveuschwarz import *
from ._gaugenonabelian import *
from ._gaugenoncommutative import *
from ._gaugenonlinear import *
from ._gaugenormalbundle import *
from ._gaugeorientifold import *
from ._gaugeperturbation import *
from ._gaugepion import *
from ._gaugeplanck import *
from ._gaugepolyakov import *
from ._gaugeproca import *
from ._gaugeprojective import *
from ._gaugequantumgravity import *
from ._gaugequark import *
from ._gaugeramond import *
from ._gaugerandommatrix import *
from ._gaugeraritaschwinger import *

__all__ = ['_gauge_decompress', 'GaugeFixedSVD', '_gauge_compress', '_gauge_decompress', 'GaugeEquivariantFFT', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeInvariantPCA', 'GaugeConnection', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeCurvature', '_gauge_compress', '_gauge_decompress', 'GaugeHolonomy', '_gauge_compress', 'GaugeWilsonLoop', '_gauge_decompress', '_gauge_compress', 'GaugeParallelTransport', '_gauge_decompress', '_gauge_compress', 'GaugeCovariantDerivative', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeFiberBundle', '_gauge_decompress', '_gauge_compress', 'GaugeSection', '_gauge_decompress', '_gauge_compress', 'GaugeTransition', '_gauge_decompress', 'GaugeCech', '_gauge_compress', '_gauge_decompress', 'GaugeSheaf', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeDifferential', '_gauge_decompress', 'GaugeIntegral', '_gauge_compress', '_gauge_decompress', 'GaugeMagnetic', '_gauge_compress', '_gauge_decompress', 'GaugeElectric', '_gauge_compress', 'GaugeMaxwell', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeYangMills', '_gauge_compress', '_gauge_decompress', 'GaugeInstantons', '_gauge_compress', '_gauge_decompress', 'GaugeMonopole', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeVortex', 'GaugeTopologicalCharge', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeChernSimons', '_gauge_compress', '_gauge_decompress', 'GaugeBRST', '_gauge_compress', 'GaugeGhost', '_gauge_decompress', '_gauge_compress', 'GaugeFaddeevPopov', '_gauge_decompress', '_gauge_compress', 'GaugeAnomaly', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeWessZumino', '_gauge_decompress', '_gauge_compress', 'GaugeTopologicalField', 'GaugeDonaldson', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeSeibergWitten', 'GaugeFloer', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeModuliSpace', '_gauge_compress', 'GaugeFlatConnection', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeAntiSelfDual', '_gauge_compress', '_gauge_decompress', 'GaugeHermitian', '_gauge_compress', '_gauge_decompress', 'GaugeStableBundle', '_gauge_compress', 'GaugeHiggsBundle', '_gauge_decompress', '_gauge_compress', 'GaugeSpectralCover', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeLanglands', '_gauge_decompress', 'GaugeSMatrix', '_gauge_compress', '_gauge_decompress', 'GaugeScattering', '_gauge_compress', 'GaugeTwistor', '_gauge_decompress', '_gauge_compress', 'GaugePenrose', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeSpinNetwork', '_gauge_decompress', 'GaugeSpinFoam', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeLoopQuantum', '_gauge_decompress', '_gauge_compress', 'GaugeAreaOperator', '_gauge_decompress', 'GaugeVolumeOperator', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeHamiltonianConstraint', '_gauge_decompress', 'GaugeDiffeoConstraint', '_gauge_compress', '_gauge_decompress', 'GaugeAshtekar', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeBarbero', '_gauge_decompress', '_gauge_compress', 'GaugeHolst', '_gauge_decompress', 'GaugePalatini', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeTetrad', '_gauge_decompress', 'GaugeSpinConnection', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeCartan', '_gauge_decompress', 'GaugeMaurerCartan', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeLieDerivative', '_gauge_decompress', '_gauge_compress', 'GaugeKilling', '_gauge_decompress', 'GaugeIsometry', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeSymplectic', '_gauge_decompress', 'GaugeKahler', '_gauge_compress', 'GaugeCalabiYau', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeSpecialHolonomy', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeG2Manifold', 'GaugeSpin7', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeExceptional', '_gauge_compress', '_gauge_decompress', 'GaugeE8', '_gauge_compress', '_gauge_decompress', 'GaugeSO32', '_gauge_compress', '_gauge_decompress', 'GaugeStringWorldsheet', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeDBNeumann', '_gauge_decompress', '_gauge_compress', 'GaugeNS5Brane', '_gauge_decompress', 'GaugeM2Brane', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeM5Brane', '_gauge_decompress', '_gauge_compress', 'GaugeSUSY', '_gauge_decompress', '_gauge_compress', 'GaugeSuperfield', '_gauge_decompress', '_gauge_compress', 'GaugeSuperConnection', '_gauge_decompress', '_gauge_compress', 'GaugeSuperCurvature', '_gauge_decompress', '_gauge_compress', 'GaugeSuperYangMills', '_gauge_decompress', 'GaugeSupergravity', '_gauge_compress', '_gauge_decompress', 'GaugeConformal', '_gauge_compress', '_gauge_decompress', 'GaugeWeyl', '_gauge_compress', 'GaugeScale', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeConformalBlock', '_gauge_decompress', 'GaugeVertexOperator', '_gauge_compress', '_gauge_decompress', 'GaugeCurrentAlgebra', '_gauge_compress', '_gauge_decompress', 'GaugeWZW', '_gauge_compress', '_gauge_decompress', 'GaugeKacMoody', '_gauge_compress', '_gauge_decompress', 'GaugeVirasoro', '_gauge_compress', '_gauge_decompress', 'GaugeCentralCharge', '_gauge_compress', 'GaugeModularInvariant', '_gauge_decompress', '_gauge_compress', 'GaugeRationalCFT', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeCosetModel', '_gauge_compress', '_gauge_decompress', 'GaugeGepner', '_gauge_compress', '_gauge_decompress', 'GaugeOrbifold', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeToric', '_gauge_decompress', '_gauge_compress', 'GaugeChernWeil', 'GaugeChernCharacter', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugePontryagin', '_gauge_decompress', '_gauge_compress', 'GaugeEuler', '_gauge_decompress', 'GaugeStiefelWhitney', '_gauge_compress', '_gauge_decompress', 'GaugeWuClass', '_gauge_compress', 'GaugeSteenrodSquare', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeTodd', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeArous', '_gauge_decompress', '_gauge_compress', 'GaugeADE', '_gauge_decompress', 'GaugeAffine', '_gauge_compress', '_gauge_decompress', 'GaugeAlmostComplex', '_gauge_compress', '_gauge_decompress', 'GaugeAtiyahSinger', '_gauge_compress', 'GaugeBogomolny', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeBPS', '_gauge_decompress', 'GaugeBTZBlackHole', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeBundleGerbe', '_gauge_decompress', '_gauge_compress', 'GaugeCanonical', '_gauge_decompress', 'GaugeCausal', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeCechDifferential', '_gauge_decompress', 'GaugeCharacteristic', '_gauge_compress', '_gauge_decompress', 'GaugeChiral', '_gauge_compress', 'GaugeCohomological', '_gauge_decompress', '_gauge_compress', 'GaugeCompact', '_gauge_decompress', '_gauge_compress', 'GaugeComplexStructure', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeCoulomb', '_gauge_compress', 'GaugeCovariantString', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeCritical', '_gauge_compress', '_gauge_decompress', 'GaugeCYCompactification', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeDeRham', 'GaugeDirac', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeDiracMonopole', '_gauge_decompress', 'GaugeDoubleCopy', '_gauge_compress', 'GaugeDual', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeDualityGroup', 'GaugeEinstein', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeEinsteinMaxwell', '_gauge_decompress', '_gauge_compress', 'GaugeElectroweak', 'GaugeEquivariantIndex', '_gauge_decompress', '_gauge_compress', 'GaugeEtaInvariant', '_gauge_decompress', '_gauge_compress', 'GaugeFTheory', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeFiberMetric', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeFreedman', '_gauge_decompress', 'GaugeFrobenius', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeFubiniStudy', '_gauge_decompress', '_gauge_compress', 'GaugeG2Holonomy', '_gauge_decompress', 'GaugeGaugino', '_gauge_compress', 'GaugeGelfandNaimark', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeGinzburgLandau', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeGluon', '_gauge_decompress', '_gauge_compress', 'GaugeGNO', '_gauge_decompress', 'GaugeGodstone', '_gauge_compress', 'GaugeGraviPhoton', '_gauge_decompress', '_gauge_compress', 'GaugeGraviton', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeGreenSchwarz', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeGrothendieckRiemannRoch', 'GaugeGroupCohomology', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeGUT', '_gauge_compress', '_gauge_decompress', 'GaugeHarmonic', '_gauge_compress', '_gauge_decompress', 'GaugeHarmonicMap', '_gauge_compress', '_gauge_decompress', 'GaugeHeterotic', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeHirzebruch', '_gauge_decompress', '_gauge_compress', 'GaugeHodgeStar', '_gauge_decompress', '_gauge_compress', 'GaugeHyperKahler', '_gauge_decompress', 'GaugeIndexTheorem', '_gauge_compress', 'GaugeIntegrableSystem', '_gauge_decompress', '_gauge_compress', 'GaugeInteracting', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeIntersection', '_gauge_decompress', 'GaugeJunction', '_gauge_compress', '_gauge_decompress', 'GaugeK3', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeKaluzaKlein', '_gauge_decompress', '_gauge_compress', 'GaugeKodaira', '_gauge_decompress', '_gauge_compress', 'GaugeLandauGinzburg', 'GaugeLargeN', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeLattice', '_gauge_compress', '_gauge_decompress', 'GaugeLichnerowicz', '_gauge_compress', 'GaugeLocalization', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeLorentz', '_gauge_compress', 'GaugeMacDowellMansouri', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeMajorana', '_gauge_compress', '_gauge_decompress', 'GaugeMassive', '_gauge_compress', 'GaugeMatrixModel', '_gauge_decompress', '_gauge_compress', 'GaugeMembrane', '_gauge_decompress', '_gauge_compress', 'GaugeMinimal', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeMirrorSymmetry', '_gauge_compress', '_gauge_decompress', 'GaugeMonodromy', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeMultiloop', '_gauge_decompress', '_gauge_compress', 'GaugeNahm', '_gauge_decompress', 'GaugeNambuGoto', '_gauge_compress', 'GaugeNeveuSchwarz', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeNonAbelian', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeNonCommutative', '_gauge_decompress', 'GaugeNonLinear', '_gauge_compress', '_gauge_decompress', 'GaugeNormalBundle', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeOrientifold', '_gauge_decompress', 'GaugePerturbation', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugePion', 'GaugePlanck', '_gauge_decompress', '_gauge_compress', 'GaugePolyakov', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeProca', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeProjective', '_gauge_decompress', 'GaugeQuantumGravity', '_gauge_compress', '_gauge_decompress', '_gauge_compress', 'GaugeQuark', '_gauge_decompress', 'GaugeRamond', '_gauge_compress', 'GaugeRandomMatrix', '_gauge_decompress', '_gauge_compress', '_gauge_decompress', 'GaugeRaritaSchwinger', '_gauge_compress']
