"""Hybrid methods combining multiple approaches."""

from ._class_wrappers import (
    Cascade2Stage,
    Cascade3Stage,
    Cascade4Stage,
    QuantizeThenSparsify,
    DecomposeThenQuantize,
    TransformThenQuantize,
    TransformThenSparsify,
    DecomposeThenTransform,
    AllMethodsEnsemble,
)
from .error_feedback import ErrorFeedbackQuant
from .working_methods import (
    generate_realistic_weights,
    method_block_int2,
    method_block_int4,
    method_block_int8,
    method_block_int8_entropy,
    method_delta_hadamard_int8,
    method_hadamard_group_int2,
    method_hadamard_group_int4,
    method_hadamard_int4_entropy,
    method_hadamard_int8,
    method_hadamard_int8_entropy,
    method_hadamard_lloydmax_int4,
    method_hadamard_lloydmax_int8,
    method_hadamard_mixed_precision,
    method_multistage_int8,
)

__all__ = [
    "Cascade2Stage",
    "Cascade3Stage",
    "Cascade4Stage",
    "QuantizeThenSparsify",
    "DecomposeThenQuantize",
    "TransformThenQuantize",
    "TransformThenSparsify",
    "DecomposeThenTransform",
    "AllMethodsEnsemble",
    "ErrorFeedbackQuant",
    "generate_realistic_weights",
    "method_block_int2",
    "method_block_int4",
    "method_block_int8",
    "method_block_int8_entropy",
    "method_delta_hadamard_int8",
    "method_hadamard_group_int2",
    "method_hadamard_group_int4",
    "method_hadamard_int4_entropy",
    "method_hadamard_int8",
    "method_hadamard_int8_entropy",
    "method_hadamard_lloydmax_int4",
    "method_hadamard_lloydmax_int8",
    "method_hadamard_mixed_precision",
    "method_multistage_int8",
]
