from __future__ import annotations

# Auto-split: original breakthrough_hybrid_massive.py split into breakthrough_hybrid_massive/
from ._svd_thenint8 import *
from ._svd_thenint4 import *
from ._svd_thennf4 import *
from ._svd_thenproductquant import *
from ._tt_thenint8 import *
from ._tt_thenint4 import *
from ._tt_thennf4 import *
from ._tt_thenproductquant import *
from ._cp_thenint8 import *
from ._cp_thenint4 import *
from ._cp_thennf4 import *
from ._tucker_thenint8 import *
from ._tucker_thenint4 import *
from ._kronecker_thenint8 import *
from ._kronecker_thenint4 import *
from ._matrixpencil_thenquant import *
from ._music_thenquant import *
from ._esprit_thenquant import *
from ._dct_thenint8 import *
from ._dct_thenint4 import *
from ._dct_thensparse import *
from ._wavelet_thenint8 import *
from ._wavelet_thenint4 import *
from ._wavelet_thensparse import *
from ._fourier_thenint8 import *
from ._fourier_thenint4 import *
from ._fourier_thensparse import *
from ._hadamard_thenint8 import *
from ._hadamard_thenint4 import *
from ._chirplet_thenquant import *
from ._fractionalfourier_thenquant import *
from ._vlasov_thenquant import *
from ._plasma_thenquant import *
from ._hamiltonian_thenquant import *
from ._gauge_thenquant import *
from ._topological_thenquant import *
from ._svd_thensparsify2of4 import *
from ._svd_thensparsifyblock import *
from ._svd_thenunstructuredprune import *
from ._tt_thensparsify import *
from ._tucker_thensparsify import *
from ._cp_thensparsify import *
from ._wavelet_thensparsify import *
from ._dct_thensparsify import *
from ._fourier_thensparsify import *
from ._svd_sparsegpt import *
from ._svd_wanda import *
from ._tt_sparsegpt import *
from ._kronecker_sparsify import *
from ._butterfly_sparsify import *
from ._monarch_sparsify import *
from ._dct_thensparsify2of4 import *
from ._dct_thensparsifyblock import *
from ._wavelet_thensparsify2of4 import *
from ._wavelet_thensparsifyblock import *
from ._fourier_thensparsify2of4 import *
from ._fourier_thensparsifyblock import *
from ._hadamard_thensparsify import *
from ._chirplet_thensparsify import *
from ._fractionalfourier_thensparsify import *
from ._vlasov_thensparsify import *
from ._hamiltonian_thensparsify import *
from ._gauge_thensparsify import *
from ._topological_thensparsify import *
from ._plasma_thensparsify import *
from ._quantum_thensparsify import *
from ._dct_tt_int8 import *
from ._wavelet_tt_int4 import *
from ._fourier_cp_nf4 import *
from ._hadamard_svd_int8 import *
from ._dct_tucker_int4 import *
from ._wavelet_tucker_int8 import *
from ._vlasov_tt_quant import *
from ._plasma_svd_int4 import *
from ._hamiltonian_tt_int8 import *
from ._gauge_svd_quant import *
from ._topological_tt_quant import *
from ._quantum_svd_int4 import *
from ._dct_svd_huffman import *
from ._wavelet_tt_rans import *
from ._fourier_cp_ans import *
from ._hadamard_tucker_zstd import *
from ._chirplet_svd_rans import *
from ._vlasov_tt_huffman import *
from ._strangeattractor_svd_quant import *
from ._koopman_tt_int8 import *
from ._kalman_svd_quant import *
from ._recurrence_tt_int4 import *
from ._synchronization_svd_int8 import *
from ._entrainment_tt_quant import *
from ._bifurcation_svd_int4 import *
from ._dct_tt_int8_rans import *
from ._wavelet_tt_int4_huffman import *
from ._fourier_cp_nf4_zstd import *
from ._hadamard_svd_int8_rans import *
from ._dct_tucker_int4_ans import *
from ._vlasov_tt_quant_rans import *
from ._plasma_svd_int4_huffman import *
from ._hamiltonian_tt_int8_zstd import *
from ._gauge_svd_quant_rans import *
from ._topological_tt_quant_ans import *
from ._quantum_svd_int4_huffman import *
from ._strangeattractor_svd_quant_rans import *
from ._koopman_tt_int8_huffman import *
from ._kalman_svd_quant_zstd import *
from ._dct_tt_int8_wavelet_huffman import *
from ._svd_dct_quant_rans import *
from ._tt_cp_nf4_zstd import *
from ._tucker_cp_quant_ans import *
from ._svd_wavelet_int4_rans import *
from ._tt_fourier_quant_huffman import *
from ._dct_svd_sparsify_quant import *
from ._wavelet_tt_sparsify_quant import *
from ._fourier_cp_sparsify_int8 import *
from ._hadamard_svd_sparsify_quant import *
from ._vlasov_tt_sparsify_rans import *
from ._ensembletop5 import *
from ._ensembletop10 import *
from ._ensembleall import *
from ._paretoensemble import *
from ._weightedensemble import *
from ._votingensemble import *
from ._baggedensemble import *
from ._boostedensemble import *
from ._stackedensemble import *
from ._cascadeensemble import *
from ._hierarchicalensemble import *
from ._adaptiveensemble import *
from ._bayesianensemble import *
from ._greedyensemble import *
from ._randomizedensemble import *
from ._adaptivedctvswavelet import *
from ._adaptivesvdvstt import *
from ._adaptivequantlevel import *
from ._adaptiveblocksize import *
from ._adaptivemethodcount import *
from ._adaptivecascade import *
from ._adaptivedecomposefirst import *
from ._adaptivetransformfirst import *
from ._adaptivesparsifyfirst import *
from ._adaptivequantizefirst import *
from ._adaptiveentropycode import *
from ._adaptivestreaming import *
from ._adaptiveparallel import *
from ._adaptivesequential import *
from ._adaptivemixed import *

__all__ = ['_as_method', 'SVD_ThenINT8', 'SVD_ThenINT4', '_as_method', 'SVD_ThenNF4', '_as_method', 'SVD_ThenProductQuant', '_as_method', '_as_method', 'TT_ThenINT8', 'TT_ThenINT4', '_as_method', 'TT_ThenNF4', '_as_method', '_as_method', 'TT_ThenProductQuant', 'CP_ThenINT8', '_as_method', 'CP_ThenINT4', '_as_method', 'CP_ThenNF4', '_as_method', 'Tucker_ThenINT8', '_as_method', 'Tucker_ThenINT4', '_as_method', 'Kronecker_ThenINT8', '_as_method', 'Kronecker_ThenINT4', '_as_method', 'MatrixPencil_ThenQuant', '_as_method', 'MUSIC_ThenQuant', '_as_method', 'ESPRIT_ThenQuant', '_as_method', 'DCT_ThenINT8', '_as_method', 'DCT_ThenINT4', '_as_method', '_as_method', 'DCT_ThenSparse', 'Wavelet_ThenINT8', '_as_method', '_as_method', 'Wavelet_ThenINT4', 'Wavelet_ThenSparse', '_as_method', 'Fourier_ThenINT8', '_as_method', 'Fourier_ThenINT4', '_as_method', 'Fourier_ThenSparse', '_as_method', 'Hadamard_ThenINT8', '_as_method', 'Hadamard_ThenINT4', '_as_method', 'Chirplet_ThenQuant', '_as_method', 'FractionalFourier_ThenQuant', '_as_method', 'Vlasov_ThenQuant', '_as_method', 'Plasma_ThenQuant', '_as_method', '_as_method', 'Hamiltonian_ThenQuant', 'Gauge_ThenQuant', '_as_method', 'Topological_ThenQuant', '_as_method', 'SVD_ThenSparsify2of4', '_as_method', '_as_method', 'SVD_ThenSparsifyBlock', '_as_method', 'SVD_ThenUnstructuredPrune', 'TT_ThenSparsify', '_as_method', 'Tucker_ThenSparsify', '_as_method', 'CP_ThenSparsify', '_as_method', 'Wavelet_ThenSparsify', '_as_method', 'DCT_ThenSparsify', '_as_method', 'Fourier_ThenSparsify', '_as_method', '_as_method', 'SVD_SparseGPT', '_as_method', 'SVD_Wanda', 'TT_SparseGPT', '_as_method', 'Kronecker_Sparsify', '_as_method', 'Butterfly_Sparsify', '_as_method', 'Monarch_Sparsify', '_as_method', 'DCT_ThenSparsify2of4', '_as_method', '_as_method', 'DCT_ThenSparsifyBlock', 'Wavelet_ThenSparsify2of4', '_as_method', '_as_method', 'Wavelet_ThenSparsifyBlock', 'Fourier_ThenSparsify2of4', '_as_method', '_as_method', 'Fourier_ThenSparsifyBlock', 'Hadamard_ThenSparsify', '_as_method', 'Chirplet_ThenSparsify', '_as_method', '_as_method', 'FractionalFourier_ThenSparsify', 'Vlasov_ThenSparsify', '_as_method', '_as_method', 'Hamiltonian_ThenSparsify', 'Gauge_ThenSparsify', '_as_method', 'Topological_ThenSparsify', '_as_method', 'Plasma_ThenSparsify', '_as_method', 'Quantum_ThenSparsify', '_as_method', 'DCT_TT_INT8', '_as_method', '_as_method', 'Wavelet_TT_INT4', 'Fourier_CP_NF4', '_as_method', 'Hadamard_SVD_INT8', '_as_method', 'DCT_Tucker_INT4', '_as_method', 'Wavelet_Tucker_INT8', '_as_method', '_as_method', 'Vlasov_TT_Quant', '_as_method', 'Plasma_SVD_INT4', 'Hamiltonian_TT_INT8', '_as_method', 'Gauge_SVD_Quant', '_as_method', '_as_method', 'Topological_TT_Quant', 'Quantum_SVD_INT4', '_as_method', 'DCT_SVD_Huffman', '_as_method', 'Wavelet_TT_rANS', '_as_method', 'Fourier_CP_ANS', '_as_method', 'Hadamard_Tucker_Zstd', '_as_method', 'Chirplet_SVD_rANS', '_as_method', 'Vlasov_TT_Huffman', '_as_method', 'StrangeAttractor_SVD_Quant', '_as_method', 'Koopman_TT_INT8', '_as_method', 'Kalman_SVD_Quant', '_as_method', 'Recurrence_TT_INT4', '_as_method', 'Synchronization_SVD_INT8', '_as_method', 'Entrainment_TT_Quant', '_as_method', 'Bifurcation_SVD_INT4', '_as_method', '_as_method', 'DCT_TT_INT8_rANS', '_as_method', 'Wavelet_TT_INT4_Huffman', 'Fourier_CP_NF4_Zstd', '_as_method', '_as_method', 'Hadamard_SVD_INT8_rANS', 'DCT_Tucker_INT4_ANS', '_as_method', 'Vlasov_TT_Quant_rANS', '_as_method', 'Plasma_SVD_INT4_Huffman', '_as_method', 'Hamiltonian_TT_INT8_Zstd', '_as_method', 'Gauge_SVD_Quant_rANS', '_as_method', 'Topological_TT_Quant_ANS', '_as_method', 'Quantum_SVD_INT4_Huffman', '_as_method', '_as_method', 'StrangeAttractor_SVD_Quant_rANS', 'Koopman_TT_INT8_Huffman', '_as_method', 'Kalman_SVD_Quant_Zstd', '_as_method', 'DCT_TT_INT8_Wavelet_Huffman', '_as_method', 'SVD_DCT_Quant_rANS', '_as_method', 'TT_CP_NF4_Zstd', '_as_method', 'Tucker_CP_Quant_ANS', '_as_method', 'SVD_Wavelet_INT4_rANS', '_as_method', '_as_method', 'TT_Fourier_Quant_Huffman', '_as_method', 'DCT_SVD_Sparsify_Quant', 'Wavelet_TT_Sparsify_Quant', '_as_method', 'Fourier_CP_Sparsify_INT8', '_as_method', '_as_method', 'Hadamard_SVD_Sparsify_Quant', 'Vlasov_TT_Sparsify_rANS', '_as_method', 'EnsembleTop5', '_as_method', '_as_method', 'EnsembleTop10', 'EnsembleAll', '_as_method', 'ParetoEnsemble', '_as_method', 'WeightedEnsemble', '_as_method', 'VotingEnsemble', '_as_method', 'BaggedEnsemble', '_as_method', 'BoostedEnsemble', '_as_method', 'StackedEnsemble', '_as_method', 'CascadeEnsemble', '_as_method', '_as_method', 'HierarchicalEnsemble', 'AdaptiveEnsemble', '_as_method', 'BayesianEnsemble', '_as_method', 'GreedyEnsemble', '_as_method', '_as_method', 'RandomizedEnsemble', 'AdaptiveDCTvsWavelet', '_as_method', '_as_method', 'AdaptiveSVDvsTT', 'AdaptiveQuantLevel', '_as_method', 'AdaptiveBlockSize', '_as_method', 'AdaptiveMethodCount', '_as_method', 'AdaptiveCascade', '_as_method', 'AdaptiveDecomposeFirst', '_as_method', 'AdaptiveTransformFirst', '_as_method', '_as_method', 'AdaptiveSparsifyFirst', '_as_method', 'AdaptiveQuantizeFirst', 'AdaptiveEntropyCode', '_as_method', 'AdaptiveStreaming', '_as_method', '_as_method', 'AdaptiveParallel', 'AdaptiveSequential', '_as_method', 'AdaptiveMixed', '_as_method']
