from __future__ import annotations

# Auto-split: original breakthrough_info_massive.py split into breakthrough_info_massive/
from ._shannonfanoelias import *
from ._tunstallcoding import *
from ._golombricecoding import *
from ._exponentialgolomb import *
from ._eliasgammacoding import *
from ._eliasdeltacoding import *
from ._eliasomegacoding import *
from ._fibonaccicoding import *
from ._unarycoding import *
from ._truncatedbinarycoding import *
from ._subexponentialcoding import *
from ._huffmanadaptive import *
from ._arithmeticadaptive import *
from ._rangecoding import *
from ._asymmetricnumeralsystems import *
from ._streamans import *
from ._interleavedans import *
from ._multisetans import *
from ._entropycodingwithcontext import *
from ._conditionalentropycoding import *
from ._predictiveentropycoding import *
from ._transformentropycoding import *
from ._blockentropycoding import *
from ._adaptiveentropycoding import *
from ._universalentropycoding import *
from ._blahutarimoto2 import *
from ._iterativerd import *
from ._lagrangianrd import *
from ._paretooptimalrd import *
from ._perceptualrd import *
from ._multiobjectiverd import *
from ._weightedrd import *
from ._constrainedrd import *
from ._variableraterd import *
from ._fixedraterd import *
from ._balancedrd import *
from ._adaptiverd import *
from ._smoothrd import *
from ._intervalrd import *
from ._surrogaterd import *
from ._deeprd import *
from ._variationalrd import *
from ._informationrd import *
from ._distortionrd import *
from ._raterd import *
from ._variationalib import *
from ._deterministicib import *
from ._conditionalib import *
from ._multiviewib import *
from ._sequentialib import *
from ._hierarchicalib import *
from ._deepib import *
from ._graphib import *
from ._adversarialib import *
from ._privacyib import *
from ._fairib import *
from ._robustib import *
from ._sparseib import *
from ._groupedib import *
from ._adaptiveib import *
from ._continuousib import *
from ._discreteib import *
from ._compressedib import *
from ._jointib import *
from ._flexibleib import *
from ._twopartmdl import *
from ._refinedmdl import *
from ._normalizedmdl import *
from ._universalmdl import *
from ._bayesianmdl import *
from ._predictivemdl import *
from ._sequentialmdl import *
from ._conditionalmdl import *
from ._hierarchicalmdl import *
from ._blockmdl import *
from ._adaptivemdl import *
from ._sparsemdl import *
from ._mixturemdl import *
from ._nonparametricmdl import *
from ._universalcodemdl import *
from ._ldpc import *
from ._turbocode import *
from ._convolutionalcode import *
from ._polarcode import *
from ._reedmuller import *
from ._bchcode import *
from ._reedsolomon import *
from ._hammingcode import *
from ._golaycode import *
from ._cycliccode import *
from ._repeataccumulate import *
from ._irregularrepeataccumulate import *
from ._spatiallycoupledldpc import *
from ._nonbinaryldpc import *
from ._staircasecode import *
from ._spinalcode import *
from ._raptorcode import *
from ._ltcode import *
from ._fountaincode import *
from ._onlinecode import *
from ._linearprediction import *
from ._autoregressiveprediction import *
from ._arimaprediction import *
from ._kalmanprediction import *
from ._particlefilterprediction import *
from ._gaussianprocessprediction import *
from ._polynomialprediction import *
from ._splineprediction import *
from ._neuralprediction import *
from ._lstmprediction import *
from ._transformerprediction import *
from ._attentionprediction import *
from ._contextbasedprediction import *
from ._adaptiveprediction import *
from ._sequentialprediction import *
from ._hierarchicalprediction import *
from ._multiscaleprediction import *
from ._multistepprediction import *
from ._errorfeedbackprediction import *
from ._residualprediction import *
from ._lloydmax import *
from ._uniformquantizer import *
from ._nonuniformquantizer import *
from ._compandingquantizer import *
from ._mulawquantizer import *
from ._alawquantizer import *
from ._logarithmicquantizer import *
from ._powerquantizer import *
from ._adaptivequantizer import *
from ._entropyconstrainedquantizer import *
from ._rateconstrainedquantizer import *
from ._distortionconstrainedquantizer import *
from ._optimalquantizer import *
from ._vectorquantizer import *
from ._latticequantizer import *
from ._shannonsourcecode import *
from ._huffmansourcecode import *
from ._arithmeticsourcecode import *
from ._lz77sourcecode import *
from ._lz78sourcecode import *
from ._lzwsourcecode import *
from ._lzmasourcecode import *
from ._bz2sourcecode import *
from ._ppmsourcecode import *
from ._ctwsourcecode import *
from ._paqsourcecode import *
from ._zpaqsourcecode import *
from ._balzsourcecode import *
from ._lzhamsourcecode import *
from ._lzsssourcecode import *

__all__ = ['_dpcm_encode', '_uniform_quantize_compress', 'ShannonFanoElias', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'TunstallCoding', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'GolombRiceCoding', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'ExponentialGolomb', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'EliasGammaCoding', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'EliasDeltaCoding', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'EliasOmegaCoding', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'FibonacciCoding', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'UnaryCoding', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'TruncatedBinaryCoding', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'SubexponentialCoding', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'HuffmanAdaptive', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', 'ArithmeticAdaptive', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'RangeCoding', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'AsymmetricNumeralSystems', '_dpcm_encode', '_uniform_quantize_compress', 'StreamANS', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'InterleavedANS', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'MultisetANS', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'EntropyCodingWithContext', 'ConditionalEntropyCoding', '_uniform_quantize_compress', '_dpcm_encode', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'PredictiveEntropyCoding', '_dpcm_encode', '_uniform_quantize_compress', 'TransformEntropyCoding', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'BlockEntropyCoding', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'AdaptiveEntropyCoding', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'UniversalEntropyCoding', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'BlahutArimoto2', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'IterativeRD', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'LagrangianRD', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'ParetoOptimalRD', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'PerceptualRD', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'MultiObjectiveRD', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'WeightedRD', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'ConstrainedRD', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'VariableRateRD', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'FixedRateRD', '_uniform_quantize_compress', '_dpcm_encode', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'BalancedRD', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'AdaptiveRD', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'SmoothRD', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'IntervalRD', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'SurrogateRD', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'DeepRD', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'VariationalRD', '_log_quantize_compress', 'InformationRD', '_uniform_quantize_compress', '_dpcm_encode', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'DistortionRD', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'RateRD', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'VariationalIB', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'DeterministicIB', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'ConditionalIB', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'MultiViewIB', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'SequentialIB', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'HierarchicalIB', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'DeepIB', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'GraphIB', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'AdversarialIB', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'PrivacyIB', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'FairIB', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'RobustIB', '_dpcm_encode', '_uniform_quantize_compress', 'SparseIB', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', 'GroupedIB', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'AdaptiveIB', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'ContinuousIB', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'DiscreteIB', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'CompressedIB', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', 'JointIB', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'FlexibleIB', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'TwoPartMDL', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'RefinedMDL', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'NormalizedMDL', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'UniversalMDL', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'BayesianMDL', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', 'PredictiveMDL', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'SequentialMDL', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'ConditionalMDL', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'HierarchicalMDL', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'BlockMDL', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'AdaptiveMDL', '_uniform_quantize_compress', '_dpcm_encode', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'SparseMDL', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', 'MixtureMDL', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'NonparametricMDL', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', 'UniversalCodeMDL', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'LDPC', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'TurboCode', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', 'ConvolutionalCode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'PolarCode', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'ReedMuller', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'BCHCode', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'ReedSolomon', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'HammingCode', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'GolayCode', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'CyclicCode', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', 'RepeatAccumulate', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'IrregularRepeatAccumulate', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'SpatiallyCoupledLDPC', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'NonbinaryLDPC', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'StaircaseCode', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'SpinalCode', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'RaptorCode', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'LTCode', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'FountainCode', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'OnlineCode', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'LinearPrediction', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'AutoregressivePrediction', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'ARIMAPrediction', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'KalmanPrediction', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'ParticleFilterPrediction', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'GaussianProcessPrediction', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'PolynomialPrediction', '_dpcm_encode', '_uniform_quantize_compress', 'SplinePrediction', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'NeuralPrediction', '_dpcm_encode', '_uniform_quantize_compress', 'LSTMPrediction', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', 'TransformerPrediction', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'AttentionPrediction', '_log_quantize_compress', 'ContextBasedPrediction', '_uniform_quantize_compress', '_dpcm_encode', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'AdaptivePrediction', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'SequentialPrediction', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'HierarchicalPrediction', '_dpcm_encode', '_uniform_quantize_compress', 'MultiScalePrediction', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'MultiStepPrediction', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'ErrorFeedbackPrediction', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'ResidualPrediction', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', 'LloydMax', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'UniformQuantizer', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'NonUniformQuantizer', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'CompandingQuantizer', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'MuLawQuantizer', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'ALawQuantizer', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'LogarithmicQuantizer', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'PowerQuantizer', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', 'AdaptiveQuantizer', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'EntropyConstrainedQuantizer', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'RateConstrainedQuantizer', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'DistortionConstrainedQuantizer', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', 'OptimalQuantizer', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'VectorQuantizer', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'LatticeQuantizer', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'ShannonSourceCode', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', 'HuffmanSourceCode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', 'ArithmeticSourceCode', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'LZ77SourceCode', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'LZ78SourceCode', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'LZWSourceCode', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'LZMASourceCode', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'BZ2SourceCode', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'PPMSourceCode', '_dpcm_encode', '_uniform_quantize_compress', 'CTWSourceCode', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', 'PAQSourceCode', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'ZPAQSourceCode', '_dpcm_encode', '_uniform_quantize_compress', 'BALZSourceCode', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', '_dpcm_encode', '_uniform_quantize_compress', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress', 'LZHAMSourceCode', '_dpcm_encode', '_uniform_quantize_compress', 'LZSSSourceCode', '_log_quantize_decompress', '_dpcm_decode', '_uniform_quantize_decompress', '_log_quantize_compress']
