from __future__ import annotations

# Auto-split: original breakthrough_math_massive.py split into breakthrough_math_massive/
from ._cyclicgroup import *
from ._dihedralgroup import *
from ._symmetricgroup import *
from ._alternatinggroup import *
from ._orthogonalgroup import *
from ._unitarygroup import *
from ._speciallineargroup import *
from ._generallineargroup import *
from ._symplecticgroup import *
from ._lorentzgroup import *
from ._poincaregroup import *
from ._euclideangroup import *
from ._affinegroup import *
from ._projectivegroup import *
from ._conformalgroup import *
from ._gaugegroup import *
from ._liegroupx import *
from ._compactgroup import *
from ._simplegroup import *
from ._reductivegroup import *
from ._specialorthogonalgroup import *
from ._specialunitarygroup import *
from ._polynomialring import *
from ._formalpowerseries import *
from ._laurentpolynomial import *
from ._groupring import *
from ._matrixring import *
from ._endomorphismring import *
from ._quotientring import *
from ._productring import *
from ._tensorproductring import *
from ._semisimplering import *
from ._artinianring import *
from ._noetherianring import *
from ._localring import *
from ._regularring import *
from ._completeintersectionring import *
from ._finitefield import *
from ._rationalfield import *
from ._numberfield import *
from ._quadraticfield import *
from ._cyclotomicfield import *
from ._functionfield import *
from ._algebraicfield import *
from ._splittingfield import *
from ._galoisfieldx import *
from ._extensionfield import *
from ._primefield import *
from ._localfield import *
from ._globalfield import *
from ._orderedfield import *
from ._completefield import *
from ._freemodule import *
from ._projectivemodule import *
from ._injectivemodule import *
from ._flatmodule import *
from ._simplemodule import *
from ._semisimplemodule import *
from ._indecomposablemodule import *
from ._gradedmodule import *
from ._filteredmodule import *
from ._torsionmodule import *
from ._torsionfreemodule import *
from ._divisiblemodule import *
from ._vermamodule import *
from ._weylmodule import *
from ._harishchandramodule import *
from ._functorcategory import *
from ._monoidalcategory import *
from ._braidedcategory import *
from ._symmetriccategory import *
from ._closedcategory import *
from ._cartesiancategory import *
from ._toposcategory import *
from ._abeliancategory import *
from ._exactcategory import *
from ._triangulatedcategory import *
from ._derivedcategoryx import *
from ._homotopycategory import *
from ._modelcategory import *
from ._infinitycategory import *
from ._enrichedcategory import *
from ._internalcategory import *
from ._bicategory import *
from ._tricategory import *
from ._doublecategory import *
from ._profunctor import *
from ._chaincomplex import *
from ._cohomologyx import *
from ._homologyx import *
from ._extgroup import *
from ._torgroup import *
from ._derivedfunctor import *
from ._spectralseqhom import *
from ._mappingcone import *
from ._mappingcylinder import *
from ._exactsequencex import *
from ._shortexactsequence import *
from ._longexactsequence import *
from ._fivelemma import *
from ._snakelemma import *
from ._zigzaglemma import *
from ._affinevariety import *
from ._projectivevariety import *
from ._quasiprojectivevariety import *
from ._scheme import *
from ._sheaf import *
from ._divisor import *
from ._linebundle import *
from ._vectorbundle import *
from ._tangentbundle import *
from ._cotangentbundle import *
from ._canonicalbundle import *
from ._amplebundle import *
from ._veryamplebundle import *
from ._globallygeneratedbundle import *
from ._nef_bundle import *
from ._riemannianmanifold import *
from ._pseudoriemannianmanifold import *
from ._symplecticmanifold import *
from ._contactmanifold import *
from ._complexmanifold import *
from ._kahlermanifold import *
from ._calabiyau import *
from ._hyperkahlermanifold import *
from ._quaternionkahlermanifold import *
from ._einsteinmanifold import *
from ._ricciflatmanifold import *
from ._constantcurvaturemanifold import *
from ._locallysymmetricspace import *
from ._homogeneousspace import *
from ._symmetricspace import *
from ._sasakianmanifold import *
from ._fundamentalgroup import *
from ._homotopygroup import *
from ._homologygroup import *
from ._cohomologygroup import *
from ._singularhomology import *
from ._simplicialhomology import *
from ._cellularhomology import *
from ._derhamcohomology import *
from ._cechcohomology import *
from ._sheafcohomology import *
from ._etalecohomologyx import *
from ._intersectionhomology import *
from ._morsehomologyx import *
from ._floerhomology import *
from ._knothomology import *
from ._borelhomology import *
from ._equivariantcohomology import *

__all__ = ['_serialize', '_reconstruct', 'CyclicGroup', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'DihedralGroup', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'SymmetricGroup', '_build_header', 'AlternatingGroup', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'OrthogonalGroup', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'UnitaryGroup', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'SpecialLinearGroup', '_build_header', 'GeneralLinearGroup', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'SymplecticGroup', '_build_header', 'LorentzGroup', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'PoincareGroup', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'EuclideanGroup', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'AffineGroup', '_build_header', '_serialize', '_reconstruct', 'ProjectiveGroup', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'ConformalGroup', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'GaugeGroup', '_build_header', 'LieGroupX', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'CompactGroup', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'SimpleGroup', '_build_header', 'ReductiveGroup', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'SpecialOrthogonalGroup', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'SpecialUnitaryGroup', '_build_header', 'PolynomialRing', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'FormalPowerSeries', '_build_header', 'LaurentPolynomial', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'GroupRing', '_build_header', 'MatrixRing', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'EndomorphismRing', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'QuotientRing', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'ProductRing', '_read_header', '_svd_core', '_build_header', 'TensorProductRing', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'SemisimpleRing', '_build_header', '_serialize', '_reconstruct', 'ArtinianRing', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'NoetherianRing', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'LocalRing', '_build_header', '_serialize', '_reconstruct', 'RegularRing', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'CompleteIntersectionRing', '_build_header', '_serialize', '_reconstruct', 'FiniteField', '_read_header', '_svd_core', '_build_header', 'RationalField', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'NumberField', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'QuadraticField', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'CyclotomicField', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'FunctionField', '_build_header', '_serialize', '_reconstruct', 'AlgebraicField', '_read_header', '_svd_core', '_build_header', 'SplittingField', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'GaloisFieldX', '_build_header', '_serialize', '_reconstruct', 'ExtensionField', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'PrimeField', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'LocalField', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'GlobalField', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'OrderedField', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'CompleteField', '_read_header', '_svd_core', '_build_header', 'FreeModule', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'ProjectiveModule', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', 'InjectiveModule', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'FlatModule', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'SimpleModule', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'SemisimpleModule', '_read_header', '_svd_core', '_build_header', '_serialize', 'IndecomposableModule', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'GradedModule', '_read_header', '_svd_core', '_build_header', 'FilteredModule', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'TorsionModule', '_build_header', '_serialize', '_reconstruct', 'TorsionFreeModule', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'DivisibleModule', '_build_header', 'VermaModule', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'WeylModule', '_build_header', '_serialize', '_reconstruct', 'HarishChandraModule', '_read_header', '_svd_core', '_build_header', 'FunctorCategory', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'MonoidalCategory', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'BraidedCategory', '_build_header', 'SymmetricCategory', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'ClosedCategory', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'CartesianCategory', '_build_header', 'ToposCategory', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'AbelianCategory', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'ExactCategory', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'TriangulatedCategory', '_read_header', '_svd_core', '_build_header', 'DerivedCategoryX', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'HomotopyCategory', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'ModelCategory', '_read_header', '_svd_core', '_build_header', 'InfinityCategory', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'EnrichedCategory', '_read_header', '_svd_core', '_build_header', '_serialize', 'InternalCategory', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'Bicategory', '_build_header', 'Tricategory', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'DoubleCategory', '_build_header', 'Profunctor', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'ChainComplex', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', 'CohomologyX', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'HomologyX', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'ExtGroup', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'TorGroup', '_build_header', '_serialize', '_reconstruct', 'DerivedFunctor', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'SpectralSeqHom', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'MappingCone', '_build_header', 'MappingCylinder', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'ExactSequenceX', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'ShortExactSequence', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'LongExactSequence', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'FiveLemma', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'SnakeLemma', '_build_header', 'ZigZagLemma', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'AffineVariety', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'ProjectiveVariety', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'QuasiProjectiveVariety', '_read_header', '_svd_core', '_build_header', 'Scheme', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'Sheaf', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'Divisor', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'LineBundle', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'VectorBundle', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'TangentBundle', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'CotangentBundle', '_build_header', 'CanonicalBundle', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'AmpleBundle', '_build_header', '_serialize', '_reconstruct', 'VeryAmpleBundle', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'GloballyGeneratedBundle', '_build_header', '_serialize', 'NEF_Bundle', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'RiemannianManifold', '_build_header', '_serialize', '_reconstruct', 'PseudoRiemannianManifold', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'SymplecticManifold', '_read_header', '_svd_core', '_build_header', 'ContactManifold', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'ComplexManifold', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'KahlerManifold', '_read_header', '_svd_core', '_build_header', 'CalabiYau', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'HyperkahlerManifold', '_build_header', 'QuaternionKahlerManifold', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'EinsteinManifold', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', 'RicciFlatManifold', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'ConstantCurvatureManifold', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'LocallySymmetricSpace', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', 'HomogeneousSpace', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'SymmetricSpace', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'SasakianManifold', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', 'FundamentalGroup', '_svd_core', '_build_header', 'HomotopyGroup', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'HomologyGroup', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'CohomologyGroup', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'SingularHomology', '_build_header', '_serialize', '_reconstruct', 'SimplicialHomology', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'CellularHomology', '_read_header', '_svd_core', '_build_header', 'deRhamCohomology', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', 'CechCohomology', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'SheafCohomology', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'EtaleCohomologyX', '_build_header', 'IntersectionHomology', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'MorseHomologyX', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', 'FloerHomology', '_read_header', '_svd_core', '_build_header', 'KnotHomology', '_serialize', '_reconstruct', '_read_header', '_svd_core', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'BorelHomology', '_build_header', '_serialize', '_reconstruct', '_read_header', '_svd_core', 'EquivariantCohomology', '_build_header']
