from __future__ import annotations

# Auto-split: original unified_physics_quantum_2.py split into unified_physics_quantum_2/
from ._unifiedfieldelectroweak import *
from ._unifiedfieldgrandunified import *
from ._unifiedfieldsupersymmetry import *
from ._unifiedfieldtechnicolor import *
from ._unifiedfieldextradimensions import *
from ._unifiedfieldseesaw import *
from ._unifiedfieldgaugecoupling import *
from ._unifiedfieldsymmetrybreaking import *
from ._unifiedfieldanomalyfree import *
from ._unifiedfieldhiggspotential import *
from ._unifiedfieldgaugemediation import *
from ._unifiedfieldplanckscale import *
from ._unifiedfieldconfinement import *
from ._unifiedfieldasymptoticfreedom import *
from ._unifiedfieldchiralperturbation import *
from ._unifiedfieldwilsonloops import *
from ._unifiedfieldtadpolecancellation import *
from ._unifiedfieldinstanton import *
from ._unifiedfieldmagneticmonopole import *
from ._unifiedfieldaxion import *
from ._unifiedfieldmajorana import *
from ._unifiedfielddirac import *
from ._unifiedfieldeffectiveaction import *
from ._unifiedfieldanomalousdimension import *
from ._unifiedfieldsmatrix import *
from ._stringcompactcalabiyau import *
from ._stringcompactorbifold import *
from ._stringcompacttorus import *
from ._stringcompactk3 import *
from ._stringcompactftheory import *
from ._stringcompactheterotic import *
from ._stringcompactmirrorsymmetry import *
from ._stringcompactfluxcompactification import *
from ._stringcompactgepnermodel import *
from ._stringcompactlandauginzburg import *
from ._stringcompactspecialholonomy import *
from ._stringcompactintersectingbranes import *
from ._stringcompactworldsheetinstantons import *
from ._stringcompacttensormanifold import *
from ._stringcompactdilaton import *
from ._stringcompactorientifold import *
from ._stringcompactmtheory import *
from ._stringcompacttypeiia import *
from ._stringcompacttypeiib import *
from ._stringcompactstringgas import *
from ._lqgspinnetwork import *
from ._lqgspinfoam import *
from ._lqgareaoperator import *
from ._lqgvolumeoperator import *
from ._lqgashtekarconnection import *
from ._lqghamiltonianconstraint import *
from ._lqgdiffeomorphismconstraint import *
from ._lqgthiemanntransform import *
from ._lqggravitonpropagator import *
from ._lqgnodeoscillator import *
from ._lqgcoherentstate import *
from ._lqgintertwiner import *
from ._lqg6jsymbol import *
from ._lqgspinorencoding import *
from ._lqgpolymerquantization import *
from ._lqgbarberoconnection import *
from ._lqgthermaltime import *
from ._lqgcausalstructure import *
from ._lqgquantumgravityeffects import *
from ._lqgloopcosmology import *
from ._twistormomentumtwistor import *
from ._twistorincidencerelation import *
from ._twistorhelicity import *
from ._twistorpenrosetransform import *
from ._twistorkerrtheorem import *
from ._twistorselfdualym import *
from ._twistorgravity import *
from ._twistormhvamplitude import *
from ._twistorintegrability import *
from ._twistorgoogly import *
from ._twistorconformalinvariance import *
from ._twistorambitwistor import *
from ._twistorstringtheory import *
from ._twistormasonsparling import *
from ._twistorcomplexstructure import *
from ._noncommutativemoyalplane import *
from ._noncommutativespectraltriple import *
from ._noncommutativeconnesdistance import *
from ._noncommutativespectralaction import *
from ._noncommutativemoritaequiv import *
from ._noncommutativekktheory import *
from ._noncommutativequantumtorus import *
from ._noncommutativefuzzysphere import *
from ._noncommutativeinstanton import *
from ._noncommutativegaugetheory import *
from ._noncommutativescalarfield import *
from ._noncommutativegravity import *
from ._noncommutativestandardmodel import *
from ._noncommutativerenormalization import *
from ._noncommutativematrixmodel import *
from ._exceptionale8 import *
from ._exceptionale7 import *
from ._exceptionale6 import *
from ._exceptionalf4 import *
from ._exceptionalg2 import *
from ._exceptionalmonstergroup import *
from ._exceptionalbabymonster import *
from ._exceptionalleechlattice import *
from ._exceptionalconwaygroup import *
from ._exceptionalfischergroup import *
from ._exceptionaljankogroup import *
from ._exceptionallietypee8 import *
from ._exceptionalcoxetergroup import *
from ._exceptionaloctonionalgebra import *
from ._exceptionaljordanalgebra import *
from ._exceptionalsporadicgroup import *
from ._exceptionalmathieugroup import *
from ._exceptionalhigmansims import *
from ._exceptionalheldgroup import *
from ._exceptionalrudvalisgroup import *
from ._categoryhighercategory import *
from ._categoryinfinitycategory import *
from ._categoryfunctor import *
from ._categorynaturaltransform import *
from ._categoryyonedalemma import *
from ._categorykanextension import *
from ._categorylimitcolimit import *
from ._categoryadjunction import *
from ._categorymonad import *
from ._categorycomonad import *
from ._categorylaxfunctor import *
from ._categorybicategory import *
from ._categoryprofunctor import *
from ._categoryendofunctor import *
from ._categoryalgebroid import *
from ._hottunivalence import *
from ._hottidentitytype import *
from ._hotthomotopygroup import *
from ._hottcontractibility import *
from ._hottfibersequence import *
from ._hotthequivalence import *
from ._hotttruncation import *
from ._hotthigherinductive import *
from ._hottcubictypetheory import *
from ._hottintervaltype import *
from ._smcbraidedcategory import *
from ._smcsymmetriccategory import *
from ._smcribboncategory import *
from ._smcrigidcategory import *
from ._smcbalancedcategory import *
from ._smctracedcategory import *
from ._smccompactcategory import *
from ._smcstarautonomous import *
from ._smcmonoidalfibration import *
from ._smcfusioncategory import *
from ._tqftstatesum import *
from ._tqftreshetikhinturaev import *
from ._tqftchernsimons import *
from ._tqftdijkgraafwitten import *
from ._tqftcobordism import *
from ._tqftfrobeniusalgebra import *
from ._tqftkitaevmodel import *
from ._tqftlevinwen import *
from ._tqftdonaldsoninvariant import *
from ._tqftseibergwitten import *
from ._physicscausaldiamond import *
from ._physicsentanglementwedge import *
from ._physicsfractontopological import *
from ._physicstimereversal import *
from ._physicsparticlevortexduality import *
from ._physicsholographicduality import *
from ._physicsemergentgravity import *
from ._physicsquantuminformation import *

__all__ = ['_serialize', '_deserialize', 'UnifiedFieldElectroweak', '_serialize', '_deserialize', 'UnifiedFieldGrandUnified', '_serialize', 'UnifiedFieldSupersymmetry', '_deserialize', '_serialize', 'UnifiedFieldTechnicolor', '_deserialize', '_serialize', 'UnifiedFieldExtraDimensions', '_deserialize', '_serialize', 'UnifiedFieldSeesaw', '_deserialize', '_serialize', '_deserialize', 'UnifiedFieldGaugeCoupling', '_serialize', '_deserialize', 'UnifiedFieldSymmetryBreaking', '_serialize', 'UnifiedFieldAnomalyFree', '_deserialize', '_serialize', '_deserialize', 'UnifiedFieldHiggsPotential', '_serialize', 'UnifiedFieldGaugeMediation', '_deserialize', '_serialize', 'UnifiedFieldPlanckScale', '_deserialize', '_serialize', '_deserialize', 'UnifiedFieldConfinement', '_serialize', 'UnifiedFieldAsymptoticFreedom', '_deserialize', '_serialize', 'UnifiedFieldChiralPerturbation', '_deserialize', '_serialize', 'UnifiedFieldWilsonLoops', '_deserialize', '_serialize', 'UnifiedFieldTadpoleCancellation', '_deserialize', '_serialize', 'UnifiedFieldInstanton', '_deserialize', '_serialize', 'UnifiedFieldMagneticMonopole', '_deserialize', '_serialize', 'UnifiedFieldAxion', '_deserialize', '_serialize', 'UnifiedFieldMajorana', '_deserialize', '_serialize', 'UnifiedFieldDirac', '_deserialize', 'UnifiedFieldEffectiveAction', '_serialize', '_deserialize', '_serialize', 'UnifiedFieldAnomalousDimension', '_deserialize', '_serialize', 'UnifiedFieldSMatrix', '_deserialize', '_serialize', 'StringCompactCalabiYau', '_deserialize', '_serialize', 'StringCompactOrbifold', '_deserialize', '_serialize', 'StringCompactTorus', '_deserialize', '_serialize', '_deserialize', 'StringCompactK3', '_serialize', 'StringCompactFTheory', '_deserialize', '_serialize', 'StringCompactHeterotic', '_deserialize', '_serialize', '_deserialize', 'StringCompactMirrorSymmetry', '_serialize', '_deserialize', 'StringCompactFluxCompactification', '_serialize', '_deserialize', 'StringCompactGepnerModel', '_serialize', '_deserialize', 'StringCompactLandauGinzburg', '_serialize', 'StringCompactSpecialHolonomy', '_deserialize', '_serialize', '_deserialize', 'StringCompactIntersectingBranes', '_serialize', 'StringCompactWorldsheetInstantons', '_deserialize', '_serialize', 'StringCompactTensorManifold', '_deserialize', '_serialize', 'StringCompactDilaton', '_deserialize', '_serialize', '_deserialize', 'StringCompactOrientifold', '_serialize', 'StringCompactMTheory', '_deserialize', '_serialize', '_deserialize', 'StringCompactTypeIIA', '_serialize', 'StringCompactTypeIIB', '_deserialize', 'StringCompactStringGas', '_serialize', '_deserialize', '_serialize', '_deserialize', 'LQGSpinNetwork', '_serialize', '_deserialize', 'LQGSpinFoam', '_serialize', '_deserialize', 'LQGAreaOperator', '_serialize', '_deserialize', 'LQGVolumeOperator', 'LQGAshtekarConnection', '_serialize', '_deserialize', '_serialize', 'LQGHamiltonianConstraint', '_deserialize', '_serialize', '_deserialize', 'LQGDiffeomorphismConstraint', 'LQGThiemannTransform', '_serialize', '_deserialize', '_serialize', 'LQGGravitonPropagator', '_deserialize', '_serialize', 'LQGNodeOscillator', '_deserialize', '_serialize', 'LQGCoherentState', '_deserialize', '_serialize', 'LQGIntertwiner', '_deserialize', '_serialize', 'LQG6JSymbol', '_deserialize', '_serialize', 'LQGSpinorEncoding', '_deserialize', '_serialize', 'LQGPolymerQuantization', '_deserialize', '_serialize', 'LQGBarberoConnection', '_deserialize', '_serialize', 'LQGThermalTime', '_deserialize', '_serialize', '_deserialize', 'LQGCausalStructure', '_serialize', 'LQGQuantumGravityEffects', '_deserialize', 'LQGLoopCosmology', '_serialize', '_deserialize', '_serialize', '_deserialize', 'TwistorMomentumTwistor', 'TwistorIncidenceRelation', '_serialize', '_deserialize', '_serialize', 'TwistorHelicity', '_deserialize', '_serialize', 'TwistorPenroseTransform', '_deserialize', '_serialize', 'TwistorKerrTheorem', '_deserialize', '_serialize', '_deserialize', 'TwistorSelfDualYM', 'TwistorGravity', '_serialize', '_deserialize', '_serialize', 'TwistorMHVAmplitude', '_deserialize', '_serialize', '_deserialize', 'TwistorIntegrability', '_serialize', 'TwistorGoogly', '_deserialize', '_serialize', 'TwistorConformalInvariance', '_deserialize', '_serialize', 'TwistorAmbitwistor', '_deserialize', '_serialize', '_deserialize', 'TwistorStringTheory', '_serialize', '_deserialize', 'TwistorMasonSparling', '_serialize', 'TwistorComplexStructure', '_deserialize', '_serialize', '_deserialize', 'NoncommutativeMoyalPlane', 'NoncommutativeSpectralTriple', '_serialize', '_deserialize', '_serialize', '_deserialize', 'NoncommutativeConnesDistance', '_serialize', '_deserialize', 'NoncommutativeSpectralAction', '_serialize', '_deserialize', 'NoncommutativeMoritaEquiv', 'NoncommutativeKKTheory', '_serialize', '_deserialize', '_serialize', '_deserialize', 'NoncommutativeQuantumTorus', '_serialize', '_deserialize', 'NoncommutativeFuzzySphere', 'NoncommutativeInstanton', '_serialize', '_deserialize', '_serialize', 'NoncommutativeGaugeTheory', '_deserialize', '_serialize', 'NoncommutativeScalarField', '_deserialize', '_serialize', 'NoncommutativeGravity', '_deserialize', 'NoncommutativeStandardModel', '_serialize', '_deserialize', '_serialize', 'NoncommutativeRenormalization', '_deserialize', '_serialize', 'NoncommutativeMatrixModel', '_deserialize', 'ExceptionalE8', '_serialize', '_deserialize', '_serialize', 'ExceptionalE7', '_deserialize', '_serialize', 'ExceptionalE6', '_deserialize', '_serialize', '_deserialize', 'ExceptionalF4', '_serialize', '_deserialize', 'ExceptionalG2', '_serialize', 'ExceptionalMonsterGroup', '_deserialize', '_serialize', 'ExceptionalBabyMonster', '_deserialize', 'ExceptionalLeechLattice', '_serialize', '_deserialize', '_serialize', '_deserialize', 'ExceptionalConwayGroup', 'ExceptionalFischerGroup', '_serialize', '_deserialize', '_serialize', '_deserialize', 'ExceptionalJankoGroup', '_serialize', 'ExceptionalLieTypeE8', '_deserialize', '_serialize', '_deserialize', 'ExceptionalCoxeterGroup', '_serialize', 'ExceptionalOctonionAlgebra', '_deserialize', '_serialize', 'ExceptionalJordanAlgebra', '_deserialize', '_serialize', '_deserialize', 'ExceptionalSporadicGroup', '_serialize', 'ExceptionalMathieuGroup', '_deserialize', '_serialize', '_deserialize', 'ExceptionalHigmanSims', '_serialize', '_deserialize', 'ExceptionalHeldGroup', '_serialize', 'ExceptionalRudvalisGroup', '_deserialize', '_serialize', '_deserialize', 'CategoryHigherCategory', '_serialize', 'CategoryInfinityCategory', '_deserialize', '_serialize', 'CategoryFunctor', '_deserialize', '_serialize', 'CategoryNaturalTransform', '_deserialize', '_serialize', 'CategoryYonedaLemma', '_deserialize', '_serialize', 'CategoryKanExtension', '_deserialize', 'CategoryLimitColimit', '_serialize', '_deserialize', '_serialize', '_deserialize', 'CategoryAdjunction', '_serialize', 'CategoryMonad', '_deserialize', '_serialize', 'CategoryComonad', '_deserialize', 'CategoryLaxFunctor', '_serialize', '_deserialize', '_serialize', 'CategoryBicategory', '_deserialize', '_serialize', 'CategoryProfunctor', '_deserialize', '_serialize', 'CategoryEndofunctor', '_deserialize', '_serialize', 'CategoryAlgebroid', '_deserialize', '_serialize', 'HottUnivalence', '_deserialize', '_serialize', '_deserialize', 'HottIdentityType', '_serialize', 'HottHomotopyGroup', '_deserialize', '_serialize', 'HottContractibility', '_deserialize', '_serialize', 'HottFiberSequence', '_deserialize', 'HottHEquivalence', '_serialize', '_deserialize', '_serialize', 'HottTruncation', '_deserialize', '_serialize', 'HottHigherInductive', '_deserialize', '_serialize', 'HottCubicTypeTheory', '_deserialize', '_serialize', 'HottIntervalType', '_deserialize', '_serialize', '_deserialize', 'SmcBraidedCategory', '_serialize', '_deserialize', 'SmcSymmetricCategory', '_serialize', 'SmcRibbonCategory', '_deserialize', '_serialize', 'SmcRigidCategory', '_deserialize', 'SmcBalancedCategory', '_serialize', '_deserialize', '_serialize', '_deserialize', 'SmcTracedCategory', '_serialize', 'SmcCompactCategory', '_deserialize', '_serialize', 'SmcStarAutonomous', '_deserialize', '_serialize', 'SmcMonoidalFibration', '_deserialize', '_serialize', '_deserialize', 'SmcFusionCategory', '_serialize', '_deserialize', 'TqftStateSum', '_serialize', 'TqftReshetikhinTuraev', '_deserialize', '_serialize', '_deserialize', 'TqftChernSimons', '_serialize', '_deserialize', 'TqftDijkgraafWitten', '_serialize', 'TqftCobordism', '_deserialize', '_serialize', 'TqftFrobeniusAlgebra', '_deserialize', '_serialize', '_deserialize', 'TqftKitaevModel', '_serialize', '_deserialize', 'TqftLevinWen', '_serialize', 'TqftDonaldsonInvariant', '_deserialize', '_serialize', 'TqftSeibergWitten', '_deserialize', '_serialize', '_deserialize', 'PhysicsCausalDiamond', '_serialize', '_deserialize', 'PhysicsEntanglementWedge', '_serialize', '_deserialize', 'PhysicsFractonTopological', '_serialize', '_deserialize', 'PhysicsTimeReversal', '_serialize', 'PhysicsParticleVortexDuality', '_deserialize', '_serialize', '_deserialize', 'PhysicsHolographicDuality', '_serialize', '_deserialize', 'PhysicsEmergentGravity', '_serialize', '_deserialize', 'PhysicsQuantumInformation']
