from ._frequencydomaincompressor import FrequencyDomainCompressor
from ._tensortraincompressor import TensorTrainCompressor
from ._residualvqcompressor import ResidualVQCompressor
from ._tensorringcompressor import TensorRingCompressor
from ._amplitudephasecompressor import AmplitudePhaseCompressor
from ._holographicweightencoder import HolographicWeightEncoder
from ._frequencyselectivetd import FrequencySelectiveTD
