from ._bit1_binarysign import Bit1_BinarySign
from ._bit1_binarythreshold import Bit1_BinaryThreshold
from ._bit1_binarystochastic import Bit1_BinaryStochastic
from ._bit1_binaryadaptive import Bit1_BinaryAdaptive
from ._bit1_binarynoiseinjection import Bit1_BinaryNoiseInjection
from ._bit2_uniform import Bit2_Uniform
from ._bit2_lloydmax import Bit2_LloydMax
from ._bit2_outlieraware import Bit2_OutlierAware
from ._bit2_adaptive import Bit2_Adaptive
from ._bit2_stochastic import Bit2_Stochastic
from ._bit2_powerlaw import Bit2_PowerLaw
from ._bit2_logarithmic import Bit2_Logarithmic
from ._bit3_uniform import Bit3_Uniform
from ._bit3_lloydmax import Bit3_LloydMax
from ._bit3_powerlaw import Bit3_PowerLaw
from ._bit3_adaptive import Bit3_Adaptive
from ._bit3_logarithmic import Bit3_Logarithmic
from ._bit3_sparseternary import Bit3_SparseTernary
from ._bit4_uniform import Bit4_Uniform
from ._bit4_lloydmax import Bit4_LloydMax
from ._bit4_powerlaw import Bit4_PowerLaw
from ._bit4_adaptive import Bit4_Adaptive
from ._bit4_mixedsignificant import Bit4_MixedSignificant
from ._bit4_logarithmic import Bit4_Logarithmic
from ._bit4_blockfloat import Bit4_BlockFloat
from ._bit4_outlierchannel import Bit4_OutlierChannel
from ._bit4_pergroup import Bit4_PerGroup
from ._bit5_uniform import Bit5_Uniform
from ._bit5_lloydmax import Bit5_LloydMax
from ._bit5_perchannel import Bit5_PerChannel
from ._bit5_adaptiveblock import Bit5_AdaptiveBlock
from ._bit5_blockfloat import Bit5_BlockFloat
from ._bit5_logarithmic import Bit5_Logarithmic
from ._bit5_powerlaw import Bit5_PowerLaw
from ._bit6_uniform import Bit6_Uniform
from ._bit6_lloydmax import Bit6_LloydMax
from ._bit6_pergroup import Bit6_PerGroup
from ._bit6_blockfloat import Bit6_BlockFloat
from ._bit6_adaptive import Bit6_Adaptive
from ._bit6_powerlaw import Bit6_PowerLaw
from ._bit6_logarithmic import Bit6_Logarithmic
from ._bit7_uniform import Bit7_Uniform
from ._bit7_lloydmax import Bit7_LloydMax
from ._bit7_perchannel import Bit7_PerChannel
from ._bit7_nearlossless import Bit7_NearLossless
from ._bit7_adaptive import Bit7_Adaptive
from ._bit7_powerlaw import Bit7_PowerLaw
from ._bit7_logarithmic import Bit7_Logarithmic
from ._bit8_symmetric import Bit8_Symmetric
from ._bit8_asymmetric import Bit8_Asymmetric
from ._bit8_perchannel import Bit8_PerChannel
from ._bit8_blockfloat import Bit8_BlockFloat
from ._bit8_adaptive import Bit8_Adaptive
from ._bit8_lloydmax import Bit8_LloydMax
from ._bit8_powerlaw import Bit8_PowerLaw
from ._bit8_logarithmic import Bit8_Logarithmic
from ._bit8_dctdomain import Bit8_DCTDomain
from ._bit9_uniform import Bit9_Uniform
from ._bit9_lloydmax import Bit9_LloydMax
from ._bit9_perchannel import Bit9_PerChannel
from ._bit9_blockfloat import Bit9_BlockFloat
from ._bit10_uniform import Bit10_Uniform
from ._bit10_lloydmax import Bit10_LloydMax
from ._bit10_perchannel import Bit10_PerChannel
from ._bit10_blockfloat import Bit10_BlockFloat
from ._bit11_uniform import Bit11_Uniform
from ._bit11_lloydmax import Bit11_LloydMax
from ._bit11_perchannel import Bit11_PerChannel
from ._bit11_blockfloat import Bit11_BlockFloat
from ._bit12_uniform import Bit12_Uniform
from ._bit12_lloydmax import Bit12_LloydMax
from ._bit12_perchannel import Bit12_PerChannel
from ._bit12_blockfloat import Bit12_BlockFloat
from ._bit13_uniform import Bit13_Uniform
from ._bit13_lloydmax import Bit13_LloydMax
from ._bit13_perchannel import Bit13_PerChannel
from ._bit13_blockfloat import Bit13_BlockFloat
from ._bit14_uniform import Bit14_Uniform
from ._bit14_lloydmax import Bit14_LloydMax
from ._bit14_perchannel import Bit14_PerChannel
from ._bit14_blockfloat import Bit14_BlockFloat
from ._bit15_uniform import Bit15_Uniform
from ._bit15_lloydmax import Bit15_LloydMax
from ._bit15_perchannel import Bit15_PerChannel
from ._bit15_blockfloat import Bit15_BlockFloat
from ._bit16_float16 import Bit16_Float16
from ._bit16_bfloat16 import Bit16_BFloat16
from ._bit16_blockfloat import Bit16_BlockFloat
from ._bit16_posit16 import Bit16_Posit16
from ._bit16_adaptive import Bit16_Adaptive
from ._bit16_lloydmax import Bit16_LloydMax
from ._bit16_logarithmic import Bit16_Logarithmic
from ._bit16_powerlaw import Bit16_PowerLaw
from ._bit16_uniform import Bit16_Uniform
from ._bit17_uniform import Bit17_Uniform
from ._bit17_lloydmax import Bit17_LloydMax
from ._bit17_blockfloat import Bit17_BlockFloat
from ._bit18_uniform import Bit18_Uniform
from ._bit18_lloydmax import Bit18_LloydMax
from ._bit18_blockfloat import Bit18_BlockFloat
from ._bit19_uniform import Bit19_Uniform
from ._bit19_lloydmax import Bit19_LloydMax
from ._bit19_blockfloat import Bit19_BlockFloat
from ._bit20_uniform import Bit20_Uniform
from ._bit20_lloydmax import Bit20_LloydMax
from ._bit20_blockfloat import Bit20_BlockFloat
from ._bit21_uniform import Bit21_Uniform
from ._bit21_lloydmax import Bit21_LloydMax
from ._bit21_blockfloat import Bit21_BlockFloat
from ._bit22_uniform import Bit22_Uniform
from ._bit22_lloydmax import Bit22_LloydMax
from ._bit22_blockfloat import Bit22_BlockFloat
from ._bit23_uniform import Bit23_Uniform
from ._bit23_lloydmax import Bit23_LloydMax
from ._bit23_blockfloat import Bit23_BlockFloat
from ._bit24_uniform import Bit24_Uniform
from ._bit24_lloydmax import Bit24_LloydMax
from ._bit24_blockfloat import Bit24_BlockFloat
from ._bit25_uniform import Bit25_Uniform
from ._bit25_lloydmax import Bit25_LloydMax
from ._bit25_blockfloat import Bit25_BlockFloat
from ._bit26_uniform import Bit26_Uniform
from ._bit26_lloydmax import Bit26_LloydMax
from ._bit26_blockfloat import Bit26_BlockFloat
from ._bit27_uniform import Bit27_Uniform
from ._bit27_lloydmax import Bit27_LloydMax
from ._bit27_blockfloat import Bit27_BlockFloat
from ._bit28_uniform import Bit28_Uniform
from ._bit28_lloydmax import Bit28_LloydMax
from ._bit28_blockfloat import Bit28_BlockFloat
from ._bit29_uniform import Bit29_Uniform
from ._bit29_lloydmax import Bit29_LloydMax
from ._bit29_blockfloat import Bit29_BlockFloat
from ._bit30_uniform import Bit30_Uniform
from ._bit30_lloydmax import Bit30_LloydMax
from ._bit30_blockfloat import Bit30_BlockFloat
from ._bit31_uniform import Bit31_Uniform
from ._bit31_lloydmax import Bit31_LloydMax
from ._bit31_blockfloat import Bit31_BlockFloat
from ._bit32_float32passthrough import Bit32_Float32Passthrough
from ._bit32_svd import Bit32_SVD
from ._bit32_dct import Bit32_DCT
from ._bit32_lossless import Bit32_Lossless
from ._bit32_adaptive import Bit32_Adaptive
from ._bit32_logarithmic import Bit32_Logarithmic
from ._bit32_powerlaw import Bit32_PowerLaw
from ._bit32_lloydmax import Bit32_LloydMax
from ._bit32_blockfloat import Bit32_BlockFloat
from ._bit32_uniform import Bit32_Uniform
from ._doublequantize import DoubleQuantize
from ._triplequantize import TripleQuantize
from ._progressivequant import ProgressiveQuant
from ._sparsequant import SparseQuant
from ._mixedprecision2 import MixedPrecision2
from ._mixedprecision3 import MixedPrecision3
from ._outlierchannel import OutlierChannel
from ._smoothquant import SmoothQuant
from ._awqlike import AWQLike
from ._gptqlike import GPTQLike
from ._qatsimulated import QATSimulated
from ._binaryternarizemixed import BinaryTernarizeMixed
from ._stochasticroundquant import StochasticRoundQuant
from ._noiseshapequant import NoiseShapeQuant
from ._gradientdescentquant import GradientDescentQuant
from ._ecp import ECP
from ._adaround import AdaRound
from ._brecgbp import BRECGBP
