from __future__ import annotations

# Auto-split: original quantization_massive.py split into quantization_massive/
from ._bit1_binarysign import *
from ._bit1_binarythreshold import *
from ._bit1_binarystochastic import *
from ._bit1_binaryadaptive import *
from ._bit1_binarynoiseinjection import *
from ._bit2_uniform import *
from ._bit2_lloydmax import *
from ._bit2_outlieraware import *
from ._bit2_adaptive import *
from ._bit2_stochastic import *
from ._bit2_powerlaw import *
from ._bit2_logarithmic import *
from ._bit3_uniform import *
from ._bit3_lloydmax import *
from ._bit3_powerlaw import *
from ._bit3_adaptive import *
from ._bit3_logarithmic import *
from ._bit3_sparseternary import *
from ._bit4_uniform import *
from ._bit4_lloydmax import *
from ._bit4_powerlaw import *
from ._bit4_adaptive import *
from ._bit4_mixedsignificant import *
from ._bit4_logarithmic import *
from ._bit4_blockfloat import *
from ._bit4_outlierchannel import *
from ._bit4_pergroup import *
from ._bit5_uniform import *
from ._bit5_lloydmax import *
from ._bit5_perchannel import *
from ._bit5_adaptiveblock import *
from ._bit5_blockfloat import *
from ._bit5_logarithmic import *
from ._bit5_powerlaw import *
from ._bit6_uniform import *
from ._bit6_lloydmax import *
from ._bit6_pergroup import *
from ._bit6_blockfloat import *
from ._bit6_adaptive import *
from ._bit6_powerlaw import *
from ._bit6_logarithmic import *
from ._bit7_uniform import *
from ._bit7_lloydmax import *
from ._bit7_perchannel import *
from ._bit7_nearlossless import *
from ._bit7_adaptive import *
from ._bit7_powerlaw import *
from ._bit7_logarithmic import *
from ._bit8_symmetric import *
from ._bit8_asymmetric import *
from ._bit8_perchannel import *
from ._bit8_blockfloat import *
from ._bit8_adaptive import *
from ._bit8_lloydmax import *
from ._bit8_powerlaw import *
from ._bit8_logarithmic import *
from ._bit8_dctdomain import *
from ._bit9_uniform import *
from ._bit9_lloydmax import *
from ._bit9_perchannel import *
from ._bit9_blockfloat import *
from ._bit10_uniform import *
from ._bit10_lloydmax import *
from ._bit10_perchannel import *
from ._bit10_blockfloat import *
from ._bit11_uniform import *
from ._bit11_lloydmax import *
from ._bit11_perchannel import *
from ._bit11_blockfloat import *
from ._bit12_uniform import *
from ._bit12_lloydmax import *
from ._bit12_perchannel import *
from ._bit12_blockfloat import *
from ._bit13_uniform import *
from ._bit13_lloydmax import *
from ._bit13_perchannel import *
from ._bit13_blockfloat import *
from ._bit14_uniform import *
from ._bit14_lloydmax import *
from ._bit14_perchannel import *
from ._bit14_blockfloat import *
from ._bit15_uniform import *
from ._bit15_lloydmax import *
from ._bit15_perchannel import *
from ._bit15_blockfloat import *
from ._bit16_float16 import *
from ._bit16_bfloat16 import *
from ._bit16_blockfloat import *
from ._bit16_posit16 import *
from ._bit16_adaptive import *
from ._bit16_lloydmax import *
from ._bit16_logarithmic import *
from ._bit16_powerlaw import *
from ._bit16_uniform import *
from ._bit17_uniform import *
from ._bit17_lloydmax import *
from ._bit17_blockfloat import *
from ._bit18_uniform import *
from ._bit18_lloydmax import *
from ._bit18_blockfloat import *
from ._bit19_uniform import *
from ._bit19_lloydmax import *
from ._bit19_blockfloat import *
from ._bit20_uniform import *
from ._bit20_lloydmax import *
from ._bit20_blockfloat import *
from ._bit21_uniform import *
from ._bit21_lloydmax import *
from ._bit21_blockfloat import *
from ._bit22_uniform import *
from ._bit22_lloydmax import *
from ._bit22_blockfloat import *
from ._bit23_uniform import *
from ._bit23_lloydmax import *
from ._bit23_blockfloat import *
from ._bit24_uniform import *
from ._bit24_lloydmax import *
from ._bit24_blockfloat import *
from ._bit25_uniform import *
from ._bit25_lloydmax import *
from ._bit25_blockfloat import *
from ._bit26_uniform import *
from ._bit26_lloydmax import *
from ._bit26_blockfloat import *
from ._bit27_uniform import *
from ._bit27_lloydmax import *
from ._bit27_blockfloat import *
from ._bit28_uniform import *
from ._bit28_lloydmax import *
from ._bit28_blockfloat import *
from ._bit29_uniform import *
from ._bit29_lloydmax import *
from ._bit29_blockfloat import *
from ._bit30_uniform import *
from ._bit30_lloydmax import *
from ._bit30_blockfloat import *
from ._bit31_uniform import *
from ._bit31_lloydmax import *
from ._bit31_blockfloat import *
from ._bit32_float32passthrough import *
from ._bit32_svd import *
from ._bit32_dct import *
from ._bit32_lossless import *
from ._bit32_adaptive import *
from ._bit32_logarithmic import *
from ._bit32_powerlaw import *
from ._bit32_lloydmax import *
from ._bit32_blockfloat import *
from ._bit32_uniform import *
from ._doublequantize import *
from ._triplequantize import *
from ._progressivequant import *
from ._sparsequant import *
from ._mixedprecision2 import *
from ._mixedprecision3 import *
from ._outlierchannel import *
from ._smoothquant import *
from ._awqlike import *
from ._gptqlike import *
from ._qatsimulated import *
from ._binaryternarizemixed import *
from ._stochasticroundquant import *
from ._noiseshapequant import *
from ._gradientdescentquant import *
from ._ecp import *
from ._adaround import *
from ._brecgbp import *

__all__ = ['_block_dequantize_flat', '_ser', '_deser', 'Bit1_BinarySign', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', 'Bit1_BinaryThreshold', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'Bit1_BinaryStochastic', '_uniform_quantize', '_lloyd_max_quantize', '_idct', 'Bit1_BinaryAdaptive', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', 'Bit1_BinaryNoiseInjection', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit2_Uniform', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', 'Bit2_LloydMax', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_uniform_quantize', '_block_quantize_flat', 'Bit2_OutlierAware', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit2_Adaptive', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', 'Bit2_Stochastic', '_idct', '_block_dequantize_flat', 'Bit2_PowerLaw', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_uniform_quantize', '_block_quantize_flat', 'Bit2_Logarithmic', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', 'Bit3_Uniform', '_idct', '_block_dequantize_flat', 'Bit3_LloydMax', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit3_PowerLaw', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', 'Bit3_Adaptive', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', 'Bit3_Logarithmic', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit3_SparseTernary', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit4_Uniform', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit4_LloydMax', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit4_PowerLaw', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', 'Bit4_Adaptive', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit4_MixedSignificant', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit4_Logarithmic', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit4_BlockFloat', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit4_OutlierChannel', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit4_PerGroup', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit5_Uniform', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit5_LloydMax', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', 'Bit5_PerChannel', '_idct', '_block_dequantize_flat', 'Bit5_AdaptiveBlock', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', 'Bit5_BlockFloat', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit5_Logarithmic', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit5_PowerLaw', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', 'Bit6_Uniform', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit6_LloydMax', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit6_PerGroup', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', 'Bit6_BlockFloat', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', 'Bit6_Adaptive', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', 'Bit6_PowerLaw', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', 'Bit6_Logarithmic', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit7_Uniform', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit7_LloydMax', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', 'Bit7_PerChannel', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit7_NearLossless', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit7_Adaptive', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', 'Bit7_PowerLaw', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', 'Bit7_Logarithmic', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', 'Bit8_Symmetric', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', 'Bit8_Asymmetric', '_idct', '_block_dequantize_flat', 'Bit8_PerChannel', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'Bit8_BlockFloat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', 'Bit8_Adaptive', '_idct', '_block_dequantize_flat', '_idct', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', 'Bit8_LloydMax', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit8_PowerLaw', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit8_Logarithmic', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit8_DCTDomain', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', 'Bit9_Uniform', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit9_LloydMax', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit9_PerChannel', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit9_BlockFloat', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_uniform_quantize', '_block_quantize_flat', 'Bit10_Uniform', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', 'Bit10_LloydMax', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'Bit10_PerChannel', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit10_BlockFloat', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'Bit11_Uniform', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit11_LloydMax', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'Bit11_PerChannel', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit11_BlockFloat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', 'Bit12_Uniform', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'Bit12_LloydMax', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', 'Bit12_PerChannel', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit12_BlockFloat', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', 'Bit13_Uniform', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit13_LloydMax', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', 'Bit13_PerChannel', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit13_BlockFloat', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', 'Bit14_Uniform', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit14_LloydMax', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit14_PerChannel', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit14_BlockFloat', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit15_Uniform', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', 'Bit15_LloydMax', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit15_PerChannel', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit15_BlockFloat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit16_Float16', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit16_BFloat16', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'Bit16_BlockFloat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit16_Posit16', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', 'Bit16_Adaptive', '_block_dequantize_flat', '_ser', 'Bit16_LloydMax', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit16_Logarithmic', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit16_PowerLaw', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit16_Uniform', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit17_Uniform', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit17_LloydMax', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit17_BlockFloat', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit18_Uniform', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit18_LloydMax', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'Bit18_BlockFloat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', 'Bit19_Uniform', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit19_LloydMax', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit19_BlockFloat', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit20_Uniform', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit20_LloydMax', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', 'Bit20_BlockFloat', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'Bit21_Uniform', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit21_LloydMax', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', 'Bit21_BlockFloat', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit22_Uniform', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit22_LloydMax', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit22_BlockFloat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'Bit23_Uniform', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', 'Bit23_LloydMax', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', 'Bit23_BlockFloat', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'Bit24_Uniform', '_uniform_quantize', '_lloyd_max_quantize', '_idct', 'Bit24_LloydMax', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit24_BlockFloat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit25_Uniform', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', 'Bit25_LloydMax', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit25_BlockFloat', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit26_Uniform', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit26_LloydMax', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit26_BlockFloat', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit27_Uniform', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', 'Bit27_LloydMax', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', 'Bit27_BlockFloat', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit28_Uniform', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit28_LloydMax', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit28_BlockFloat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit29_Uniform', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit29_LloydMax', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit29_BlockFloat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit30_Uniform', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', 'Bit30_LloydMax', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'Bit30_BlockFloat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', 'Bit31_Uniform', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'Bit31_LloydMax', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', 'Bit31_BlockFloat', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit32_Float32Passthrough', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit32_SVD', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit32_DCT', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit32_Lossless', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit32_Adaptive', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'Bit32_Logarithmic', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit32_PowerLaw', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'Bit32_LloydMax', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'Bit32_BlockFloat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'Bit32_Uniform', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'DoubleQuantize', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'TripleQuantize', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'ProgressiveQuant', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'SparseQuant', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'MixedPrecision2', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', 'MixedPrecision3', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'OutlierChannel', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_uniform_quantize', '_block_quantize_flat', 'SmoothQuant', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'AWQLike', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'GPTQLike', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'QATSimulated', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', 'BinaryTernarizeMixed', '_idct', '_block_dequantize_flat', '_ser', '_deser', 'StochasticRoundQuant', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', 'NoiseShapeQuant', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'GradientDescentQuant', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', 'ECP', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', '_uniform_quantize', '_lloyd_max_quantize', 'AdaRound', '_idct', '_block_dequantize_flat', '_ser', '_deser', '_per_channel_quantize', '_dct', '_block_quantize_flat', 'BRECGBP', '_uniform_quantize', '_lloyd_max_quantize', '_idct']
