from __future__ import annotations

import math
import struct
from typing import Any, Tuple

import numpy as np


def _serialize(arr: np.ndarray) -> bytes:
    return arr.astype(np.float32).tobytes()

def _deserialize(data: bytes, dtype=np.float32) -> np.ndarray:
    return np.frombuffer(data, dtype=dtype).copy()

def _next_power_of_two(n: int) -> int:
    return 1 << (n - 1).bit_length()

class LatticeQFT:
    """Lattice field theory: the weight matrix is a classical field
    configuration on a lattice. Store only the action parameters
    (mass m, coupling g) and the coarse-grained field. The fine
    structure is generated by stochastic quantization (Langevin).

    Real: coarse-grain via block averaging + store residual statistics
    as action parameters. Reconstruction = upsampling + noise with
    correct correlation structure.
    """

    name = "lattice_qft"
    category = "breakthrough_physics"

    def compress(
        self, tensor: np.ndarray, coarse_factor: int = 4
    ) -> Tuple[bytes, dict]:
        t = tensor.astype(np.float64)
        m, n = t.shape
        cf = min(coarse_factor, m, n)
        cm, cn = max(1, m // cf), max(1, n // cf)
        # Coarse-grain: block average
        coarse = np.zeros((cm, cn), dtype=np.float64)
        for i in range(cm):
            for j in range(cn):
                block = t[
                    i * cf : min((i + 1) * cf, m),
                    j * cf : min((j + 1) * cf, n),
                ]
                coarse[i, j] = float(np.mean(block))
        # Residual statistics = action parameters
        residual = t - np.kron(coarse, np.ones((cf, cf))[:m, :n])
        mass = float(1.0 / (np.std(residual) + 1e-10))
        coupling = float(np.mean(residual**4) / (np.mean(residual**2) + 1e-10) ** 2)
        # Quantize coarse field
        coarse_flat = coarse.ravel().astype(np.float32)
        coarse_quant = np.clip(
            np.round(coarse_flat * 127.0 / max(np.max(np.abs(coarse_flat)), 1e-10)),
            -128,
            127,
        ).astype(np.int8)
        c_scale = float(max(np.max(np.abs(coarse_flat)), 1e-10) / 127.0)
        buf = struct.pack("<IIff", cm, cn, mass, coupling)
        buf += struct.pack("<f", c_scale)
        buf += coarse_quant.tobytes()
        return bytes(buf), {
            "shape": tensor.shape,
            "m": m,
            "n": n,
            "cm": cm,
            "cn": cn,
            "coarse_factor": cf,
            "mass": mass,
            "coupling": coupling,
        }

    def decompress(self, data: bytes, metadata: dict) -> np.ndarray:
        cm, cn, mass, coupling = struct.unpack_from("<IIff", data, 0)
        pos = 16
        c_scale = struct.unpack_from("<f", data, pos)[0]
        pos += 4
        coarse_quant = np.frombuffer(data[pos : pos + cm * cn], dtype=np.int8)
        coarse = coarse_quant.astype(np.float32) * c_scale
        coarse_2d = coarse.reshape(cm, cn)
        cf = metadata.get("coarse_factor", 4)
        m, n = metadata["shape"]
        # Upsample with smoothing (lattice field interpolation)
        recon = np.zeros((m, n), dtype=np.float64)
        for i in range(m):
            ci = min(i // cf, cm - 1)
            for j in range(n):
                cj = min(j // cf, cn - 1)
                recon[i, j] = coarse_2d[ci, cj]
        # Add quantum fluctuations with correct correlation
        noise = np.random.RandomState(42).randn(m, n).astype(np.float64)
        smooth_noise = (
            noise
            + np.roll(noise, 1, axis=0)
            + np.roll(noise, -1, axis=0)
            + np.roll(noise, 1, axis=1)
            + np.roll(noise, -1, axis=1)
        ) / 5.0
        fluct_scale = 1.0 / max(mass, 1e-10)
        recon += smooth_noise * fluct_scale * 0.01
        return recon.astype(np.float32)
