from __future__ import annotations

# Auto-split: original sparsity_transform_delta_massive.py split into sparsity_transform_delta_massive/
from ._sparsity1of2 import *
from ._sparsity1of4 import *
from ._sparsity2of4 import *
from ._sparsity3of4 import *
from ._sparsity1of8 import *
from ._sparsity2of8 import *
from ._sparsity3of8 import *
from ._sparsity4of8 import *
from ._sparsity1of16 import *
from ._sparsity2of16 import *
from ._sparsity4of16 import *
from ._sparsity8of16 import *
from ._randomsparsitypattern import *
from ._structuredsparsitypattern import *
from ._blocksparsitypattern import *
from ._stridedsparsitypattern import *
from ._diagonalsparsitypattern import *
from ._bandedsparsitypattern import *
from ._adaptivesparsitypattern import *
from ._learnedsparsitypattern import *
from ._blocksize16 import *
from ._blocksize32 import *
from ._blocksize64 import *
from ._blocksize128 import *
from ._blocksize256 import *
from ._adaptiveblocksize import *
from ._variableblocksize import *
from ._hierarchicalblock import *
from ._overlappingblock import *
from ._tiledblock import *
from ._stripedblock import *
from ._checkerboardblock import *
from ._diagonalblock import *
from ._bandedblock import *
from ._outerproductblock import *
from ._magnitudepruning import *
from ._randompruning import *
from ._gradientpruning import *
from ._hessianpruning import *
from ._movementpruning import *
from ._lotteryticketpruning import *
from ._iterativepruning import *
from ._oneshotpruning import *
from ._gradualpruning import *
from ._rewindingpruning import *
from ._globalpruning import *
from ._localpruning import *
from ._layerwisepruning import *
from ._thresholdpruning import *
from ._adaptivepruning import *
from ._sparseint8 import *
from ._sparseint4 import *
from ._sparsenf4 import *
from ._sparseternary import *
from ._sparsebinary import *
from ._sparseproductquant import *
from ._sparseresidualquant import *
from ._sparsekmeans import *
from ._blocksparseint8 import *
from ._blocksparseint4 import *
from ._nmsparseint8 import *
from ._nmsparseint4 import *
from ._diagonalsparseint8 import *
from ._bandedsparseint8 import *
from ._randomsparseint8 import *
from ._topkweightsparseint4 import *
from ._topkblocksparseint4 import *
from ._outliersparseint8 import *
from ._structuredsparseint4 import *
from ._adaptivesparsequant import *
from ._circulantsparse import *
from ._toeplitzsparse import *
from ._hankelsparse import *
from ._vandermondesparse import *
from ._butterflysparse import *
from ._monarchsparse import *
from ._fft_sparse import *
from ._dct_sparse import *
from ._waveletsparse import *
from ._hadamardsparse import *
from ._kroneckersparse import *
from ._cauchysparse import *
from ._chebyshevsparse import *
from ._legendresparse import *
from ._fouriersparse import *
from ._gpu_friendlysparsity import *
from ._cpu_friendlysparsity import *
from ._simd_sparsity import *
from ._cachefriendlysparsity import *
from ._memoryalignedsparsity import *
from ._vectorizedsparsity import *
from ._tensorcoresparsity import *
from ._npu_sparsity import *
from ._tpu_sparsity import *
from ._fpga_sparsity import *
from ._asic_sparsity import *
from ._mobilesparsity import *
from ._edgesparsity import *
from ._distributedsparsity import *
from ._parallelsparsity import *
from ._dct4x4_quant import *
from ._dct8x8_quant import *
from ._dct16x16_quant import *
from ._dct32x32_quant import *
from ._dct_block4_quant import *
from ._dct_block8_quant import *
from ._dct_block16_quant import *
from ._dct_adaptiveblock_quant import *
from ._dct_energythreshold_quant import *
from ._dct_zigzag_quant import *
from ._dct_jpeg_quant import *
from ._dct_mpeg_quant import *
from ._dct_h265_quant import *
from ._dct_av1_quant import *
from ._dct_vc6_quant import *
from ._dct_vp9_quant import *
from ._dct_theora_quant import *
from ._dct_dirac_quant import *
from ._dct_wmv_quant import *
from ._dct_vc1_quant import *
from ._haarwavelet_quant import *
from ._daubechies4_quant import *
from ._daubechies6_quant import *
from ._daubechies8_quant import *
from ._symlet4_quant import *
from ._symlet6_quant import *
from ._coiflet2_quant import *
from ._coiflet4_quant import *
from ._biorthogonal_quant import *
from ._reversebiorthogonal_quant import *
from ._discretemeyer_quant import *
from ._battlelemarie_quant import *
from ._splinewavelet_quant import *
from ._morletwavelet_quant import *
from ._mexicanhat_quant import *
from ._complexwavelet_quant import *
from ._dualtreewavelet_quant import *
from ._waveletpacket_quant import *
from ._stationarywavelet_quant import *
from ._liftingwavelet_quant import *
from ._fft_quant import *
from ._rfft_quant import *
from ._dst_quant import *
from ._dht_quant import *
from ._dft_quant import *
from ._fractionalfft_quant import *
from ._goertzel_quant import *
from ._chirpz_quant import *
from ._zoomfft_quant import *
from ._slidingdft_quant import *
from ._prunedfft_quant import *
from ._sparsefft_quant import *
from ._realfft_quant import *
from ._complexfft_quant import *
from ._multidimensionalfft_quant import *
from ._hadamard_quant import *
from ._orderedhadamard_quant import *
from ._sequencyhadamard_quant import *
from ._dyadichadamard_quant import *
from ._walshhadamard_quant import *
from ._slanthadamard_quant import *
from ._complexhadamard_quant import *
from ._quaternionhadamard_quant import *
from ._fractionalhadamard_quant import *
from ._permutedhadamard_quant import *
from ._scrambledhadamard_quant import *
from ._adaptivehadamard_quant import *
from ._blockhadamard_quant import *
from ._hierarchicalhadamard_quant import *
from ._mixedradixhadamard_quant import *
from ._klt_quant import *
from ._adaptiveklt_quant import *
from ._blockklt_quant import *
from ._segmentklt_quant import *
from ._recursiveklt_quant import *
from ._fastklt_quant import *
from ._approximateklt_quant import *
from ._sparseklt_quant import *
from ._robustklt_quant import *
from ._incrementalklt_quant import *
from ._sinetransform_quant import *
from ._cosinetransform_quant import *
from ._hartleytransform_quant import *
from ._hilberttransform_quant import *
from ._cepstraltransform_quant import *
from ._mellintransform_quant import *
from ._ztransform_quant import *
from ._laplacetransform_quant import *
from ._ridgelettransform_quant import *
from ._curvelettransform_quant import *
from ._contourlettransform_quant import *
from ._shearlettransform_quant import *
from ._bandlettransform_quant import *
from ._wedgelettransform_quant import *
from ._platelettransform_quant import *
from ._surflettransform_quant import *
from ._beamlettransform_quant import *
from ._chordlettransform_quant import *
from ._arbitrarytransform_quant import *
from ._sequentialdelta import *
from ._framedelta import *
from ._interframedelta import *
from ._intraframedelta import *
from ._adaptivedelta import *
from ._hierarchicaldelta import *
from ._multiscaledelta import *
from ._variabledelta import *
from ._predictivedelta import *
from ._bidirectionaldelta import *
from ._motioncompensateddelta import *
from ._weighteddelta import *
from ._sparsedelta import *
from ._thresholdeddelta import *
from ._quantizeddelta import *
from ._entropycodeddelta import *
from ._runlengthdelta import *
from ._dictionarydelta import *
from ._transformdelta import *
from ._hybriddelta import *
from ._layerdelta import *
from ._interlayerdelta import *
from ._intralayerdelta import *
from ._adjacentlayerdelta import *
from ._skiplayerdelta import *
from ._residuallayerdelta import *
from ._attentiondelta import *
from ._ffn_delta import *
from ._embeddingdelta import *
from ._headdelta import *
from ._expertdelta import *
from ._shareddelta import *
from ._normdelta import *
from ._biasdelta import *
from ._weightdelta import *
from ._gradientdelta import *
from ._activationdelta import *
from ._blockdelta import *
from ._channeldelta import *
from ._rowdelta import *
from ._linearpredictivedelta import *
from ._ar_delta import *
from ._ma_delta import *
from ._arma_delta import *
from ._kalmandelta import *
from ._particledelta import *
from ._gp_delta import *
from ._neuraldelta import *
from ._lstm_delta import *
from ._attentiondeltapred import *
from ._transformerdelta import *
from ._contextdelta import *
from ._adaptivepredictivedelta import *
from ._multisteppredictivedelta import *
from ._errorfeedbackdelta import *
from ._gradientdeltapred import *
from ._hessiandeltapred import *
from ._momentumdeltapred import *
from ._nesterovdelta import *
from ._adamdelta import *
from ._rowdeltastructured import *
from ._columndelta import *
from ._blockdeltastructured import *
from ._diagonaldelta import *
from ._bandeddelta import *
from ._triangulardelta import *
from ._symmetricdelta import *
from ._circulantdelta import *
from ._toeplitzdelta import *
from ._hankeldelta import *
from ._vandermondedelta import *
from ._cauchydelta import *
from ._permutationdelta import *
from ._kroneckerdelta import *
from ._butterflydelta import *
from ._monarchdelta import *
from ._svd_delta import *
from ._cp_delta import *
from ._tt_delta import *
from ._tucker_delta import *
from ._adaptivethresholddelta import *
from ._adaptiveblockdelta import *
from ._adaptivestepdelta import *
from ._adaptivequantdelta import *
from ._adaptivepredictordelta import *
from ._adaptiveerrordelta import *
from ._learningratedelta import *
from ._momentumdelta import *
from ._signdelta import *
from ._exponentialdelta import *
from ._logarithmicdelta import *
from ._powerdelta import *
from ._piecewisedelta import *
from ._splinedelta import *
from ._interpolatingdelta import *
from ._extrapolatingdelta import *
from ._smoothingdelta import *
from ._filteringdelta import *
from ._mediandelta import *
from ._modedelta import *
from ._topksparsity import *
from ._bottomksparsity import *
from ._percentilesparsity import *
from ._dynamicsparsity import *
from ._staticsparsity import *
from ._uniformsparsity import *
from ._erdosrenyisparsity import *
from ._powerlawsparsity import *
from ._l1sparsity import *
from ._l0sparsity import *
from ._karhunenloeve_quant import *
from ._independentcomponent_quant import *
from ._principalcomponent_quant import *
from ._nonnegativematrix_quant import *
from ._sparsecoding_quant import *
from ._temporaldelta import *
from ._spatialdelta import *
from ._spatiotemporaldelta import *
from ._frequencydelta import *
from ._phasedelta import *

__all__ = ['_ser', 'Sparsity1of2', '_ser', 'Sparsity1of4', '_ser', 'Sparsity2of4', '_ser', 'Sparsity3of4', '_ser', 'Sparsity1of8', '_ser', 'Sparsity2of8', '_ser', 'Sparsity3of8', '_ser', 'Sparsity4of8', 'Sparsity1of16', '_ser', '_ser', 'Sparsity2of16', 'Sparsity4of16', '_ser', '_ser', 'Sparsity8of16', '_ser', 'RandomSparsityPattern', '_ser', 'StructuredSparsityPattern', '_ser', 'BlockSparsityPattern', 'StridedSparsityPattern', '_ser', '_ser', 'DiagonalSparsityPattern', '_ser', 'BandedSparsityPattern', '_ser', 'AdaptiveSparsityPattern', '_ser', 'LearnedSparsityPattern', '_ser', 'BlockSize16', '_ser', 'BlockSize32', '_ser', 'BlockSize64', '_ser', 'BlockSize128', 'BlockSize256', '_ser', 'AdaptiveBlockSize', '_ser', '_ser', 'VariableBlockSize', '_ser', 'HierarchicalBlock', '_ser', 'OverlappingBlock', '_ser', 'TiledBlock', '_ser', 'StripedBlock', '_ser', 'CheckerboardBlock', '_ser', 'DiagonalBlock', '_ser', 'BandedBlock', '_ser', 'OuterProductBlock', '_ser', 'MagnitudePruning', '_ser', 'RandomPruning', '_ser', 'GradientPruning', '_ser', 'HessianPruning', '_ser', 'MovementPruning', '_ser', 'LotteryTicketPruning', '_ser', 'IterativePruning', '_ser', 'OneShotPruning', '_ser', 'GradualPruning', '_ser', 'RewindingPruning', '_ser', 'GlobalPruning', '_ser', 'LocalPruning', '_ser', 'LayerwisePruning', 'ThresholdPruning', '_ser', '_ser', 'AdaptivePruning', '_ser', 'SparseINT8', '_ser', 'SparseINT4', '_ser', 'SparseNF4', 'SparseTernary', '_ser', '_ser', 'SparseBinary', '_ser', 'SparseProductQuant', '_ser', 'SparseResidualQuant', '_ser', 'SparseKMeans', '_ser', 'BlockSparseINT8', '_ser', 'BlockSparseINT4', '_ser', 'NMSparseINT8', '_ser', 'NMSparseINT4', '_ser', 'DiagonalSparseINT8', 'BandedSparseINT8', '_ser', '_ser', 'RandomSparseINT8', 'TopKWeightSparseINT4', '_ser', '_ser', 'TopKBlockSparseINT4', '_ser', 'OutlierSparseINT8', '_ser', 'StructuredSparseINT4', '_ser', 'AdaptiveSparseQuant', '_ser', 'CirculantSparse', '_ser', 'ToeplitzSparse', '_ser', 'HankelSparse', 'VandermondeSparse', '_ser', '_ser', 'ButterflySparse', '_ser', 'MonarchSparse', '_ser', 'FFT_Sparse', '_ser', 'DCT_Sparse', 'WaveletSparse', '_ser', '_ser', 'HadamardSparse', '_ser', 'KroneckerSparse', '_ser', 'CauchySparse', '_ser', 'ChebyshevSparse', '_ser', 'LegendreSparse', '_ser', 'FourierSparse', '_ser', 'GPU_FriendlySparsity', '_ser', 'CPU_FriendlySparsity', '_ser', 'SIMD_Sparsity', '_ser', 'CacheFriendlySparsity', '_ser', 'MemoryAlignedSparsity', '_ser', 'VectorizedSparsity', '_ser', 'TensorCoreSparsity', 'NPU_Sparsity', '_ser', '_ser', 'TPU_Sparsity', '_ser', 'FPGA_Sparsity', '_ser', 'ASIC_Sparsity', 'MobileSparsity', '_ser', '_ser', 'EdgeSparsity', '_ser', 'DistributedSparsity', '_ser', 'ParallelSparsity', '_ser', 'DCT4x4_Quant', '_ser', 'DCT8x8_Quant', '_ser', 'DCT16x16_Quant', '_ser', 'DCT32x32_Quant', '_ser', 'DCT_Block4_Quant', '_ser', 'DCT_Block8_Quant', '_ser', 'DCT_Block16_Quant', '_ser', 'DCT_AdaptiveBlock_Quant', '_ser', 'DCT_EnergyThreshold_Quant', '_ser', 'DCT_Zigzag_Quant', '_ser', 'DCT_JPEG_Quant', '_ser', 'DCT_MPEG_Quant', '_ser', 'DCT_H265_Quant', '_ser', 'DCT_AV1_Quant', '_ser', 'DCT_VC6_Quant', 'DCT_VP9_Quant', '_ser', '_ser', 'DCT_Theora_Quant', '_ser', 'DCT_Dirac_Quant', '_ser', 'DCT_WMV_Quant', '_ser', 'DCT_VC1_Quant', 'HaarWavelet_Quant', '_ser', 'Daubechies4_Quant', '_ser', '_ser', 'Daubechies6_Quant', 'Daubechies8_Quant', '_ser', 'Symlet4_Quant', '_ser', '_ser', 'Symlet6_Quant', '_ser', 'Coiflet2_Quant', '_ser', 'Coiflet4_Quant', '_ser', 'Biorthogonal_Quant', '_ser', 'ReverseBiorthogonal_Quant', '_ser', 'DiscreteMeyer_Quant', '_ser', 'BattleLemarie_Quant', '_ser', 'SplineWavelet_Quant', '_ser', 'MorletWavelet_Quant', '_ser', 'MexicanHat_Quant', '_ser', 'ComplexWavelet_Quant', '_ser', 'DualTreeWavelet_Quant', 'WaveletPacket_Quant', '_ser', '_ser', 'StationaryWavelet_Quant', '_ser', 'LiftingWavelet_Quant', 'FFT_Quant', '_ser', '_ser', 'RFFT_Quant', '_ser', 'DST_Quant', '_ser', 'DHT_Quant', 'DFT_Quant', '_ser', '_ser', 'FractionalFFT_Quant', '_ser', 'Goertzel_Quant', '_ser', 'ChirpZ_Quant', '_ser', 'ZoomFFT_Quant', '_ser', 'SlidingDFT_Quant', '_ser', 'PrunedFFT_Quant', '_ser', 'SparseFFT_Quant', 'RealFFT_Quant', '_ser', '_ser', 'ComplexFFT_Quant', '_ser', 'MultidimensionalFFT_Quant', '_ser', 'Hadamard_Quant', '_ser', 'OrderedHadamard_Quant', '_ser', 'SequencyHadamard_Quant', '_ser', 'DyadicHadamard_Quant', '_ser', 'WalshHadamard_Quant', '_ser', 'SlantHadamard_Quant', '_ser', 'ComplexHadamard_Quant', '_ser', 'QuaternionHadamard_Quant', '_ser', 'FractionalHadamard_Quant', '_ser', 'PermutedHadamard_Quant', '_ser', 'ScrambledHadamard_Quant', '_ser', 'AdaptiveHadamard_Quant', '_ser', 'BlockHadamard_Quant', '_ser', 'HierarchicalHadamard_Quant', '_ser', 'MixedRadixHadamard_Quant', '_ser', 'KLT_Quant', '_ser', 'AdaptiveKLT_Quant', '_ser', 'BlockKLT_Quant', '_ser', 'SegmentKLT_Quant', '_ser', 'RecursiveKLT_Quant', '_ser', 'FastKLT_Quant', '_ser', 'ApproximateKLT_Quant', '_ser', 'SparseKLT_Quant', '_ser', 'RobustKLT_Quant', '_ser', 'IncrementalKLT_Quant', '_ser', 'SineTransform_Quant', '_ser', 'CosineTransform_Quant', '_ser', 'HartleyTransform_Quant', '_ser', 'HilbertTransform_Quant', '_ser', 'CepstralTransform_Quant', '_ser', 'MellinTransform_Quant', '_ser', 'ZTransform_Quant', '_ser', 'LaplaceTransform_Quant', '_ser', 'RidgeletTransform_Quant', '_ser', 'CurveletTransform_Quant', 'ContourletTransform_Quant', '_ser', '_ser', 'ShearletTransform_Quant', '_ser', 'BandletTransform_Quant', '_ser', 'WedgeletTransform_Quant', '_ser', 'PlateletTransform_Quant', '_ser', 'SurfletTransform_Quant', '_ser', 'BeamletTransform_Quant', '_ser', 'ChordletTransform_Quant', '_ser', 'ArbitraryTransform_Quant', '_ser', 'SequentialDelta', '_ser', 'FrameDelta', '_ser', 'InterFrameDelta', '_ser', 'IntraFrameDelta', '_ser', 'AdaptiveDelta', '_ser', 'HierarchicalDelta', '_ser', 'MultiScaleDelta', '_ser', 'VariableDelta', '_ser', 'PredictiveDelta', '_ser', 'BidirectionalDelta', 'MotionCompensatedDelta', '_ser', 'WeightedDelta', '_ser', '_ser', 'SparseDelta', '_ser', 'ThresholdedDelta', '_ser', 'QuantizedDelta', '_ser', 'EntropyCodedDelta', '_ser', 'RunLengthDelta', '_ser', 'DictionaryDelta', '_ser', 'TransformDelta', '_ser', 'HybridDelta', '_ser', 'LayerDelta', '_ser', 'InterLayerDelta', '_ser', 'IntraLayerDelta', '_ser', 'AdjacentLayerDelta', '_ser', 'SkipLayerDelta', 'ResidualLayerDelta', '_ser', '_ser', 'AttentionDelta', '_ser', 'FFN_Delta', '_ser', 'EmbeddingDelta', '_ser', 'HeadDelta', '_ser', 'ExpertDelta', 'SharedDelta', '_ser', '_ser', 'NormDelta', '_ser', 'BiasDelta', '_ser', 'WeightDelta', '_ser', 'GradientDelta', '_ser', 'ActivationDelta', '_ser', 'BlockDelta', '_ser', 'ChannelDelta', '_ser', 'RowDelta', '_ser', 'LinearPredictiveDelta', '_ser', 'AR_Delta', '_ser', 'MA_Delta', '_ser', 'ARMA_Delta', '_ser', 'KalmanDelta', 'ParticleDelta', '_ser', 'GP_Delta', '_ser', '_ser', 'NeuralDelta', 'LSTM_Delta', '_ser', '_ser', 'AttentionDeltaPred', '_ser', 'TransformerDelta', '_ser', 'ContextDelta', '_ser', 'AdaptivePredictiveDelta', 'MultiStepPredictiveDelta', '_ser', '_ser', 'ErrorFeedbackDelta', '_ser', 'GradientDeltaPred', '_ser', 'HessianDeltaPred', '_ser', 'MomentumDeltaPred', '_ser', 'NesterovDelta', '_ser', 'AdamDelta', '_ser', 'RowDeltaStructured', '_ser', 'ColumnDelta', 'BlockDeltaStructured', '_ser', '_ser', 'DiagonalDelta', '_ser', 'BandedDelta', '_ser', 'TriangularDelta', '_ser', 'SymmetricDelta', '_ser', 'CirculantDelta', '_ser', 'ToeplitzDelta', '_ser', 'HankelDelta', '_ser', 'VandermondeDelta', 'CauchyDelta', '_ser', '_ser', 'PermutationDelta', '_ser', 'KroneckerDelta', '_ser', 'ButterflyDelta', '_ser', 'MonarchDelta', '_ser', 'SVD_Delta', '_ser', 'CP_Delta', '_ser', 'TT_Delta', '_ser', 'Tucker_Delta', '_ser', 'AdaptiveThresholdDelta', '_ser', 'AdaptiveBlockDelta', '_ser', 'AdaptiveStepDelta', 'AdaptiveQuantDelta', '_ser', '_ser', 'AdaptivePredictorDelta', '_ser', 'AdaptiveErrorDelta', '_ser', 'LearningRateDelta', '_ser', 'MomentumDelta', '_ser', 'SignDelta', '_ser', 'ExponentialDelta', '_ser', 'LogarithmicDelta', '_ser', 'PowerDelta', '_ser', 'PiecewiseDelta', '_ser', 'SplineDelta', '_ser', 'InterpolatingDelta', '_ser', 'ExtrapolatingDelta', '_ser', 'SmoothingDelta', '_ser', 'FilteringDelta', '_ser', 'MedianDelta', '_ser', 'ModeDelta', '_ser', 'TopKSparsity', '_ser', 'BottomKSparsity', '_ser', 'PercentileSparsity', '_ser', 'DynamicSparsity', '_ser', 'StaticSparsity', '_ser', 'UniformSparsity', '_ser', 'ErdosRenyiSparsity', '_ser', 'PowerLawSparsity', '_ser', 'L1Sparsity', '_ser', 'L0Sparsity', '_ser', 'KarhunenLoeve_Quant', '_ser', 'IndependentComponent_Quant', '_ser', 'PrincipalComponent_Quant', '_ser', 'NonNegativeMatrix_Quant', '_ser', 'SparseCoding_Quant', '_ser', 'TemporalDelta', 'SpatialDelta', '_ser', '_ser', 'SpatioTemporalDelta', '_ser', 'FrequencyDelta', '_ser', 'PhaseDelta']
